# Introduction to Pandas

Pandas is a package built on top of numpy which incorporates many additional features which make it more convenient for data analysis. One main addition is the inclusion of row and column labels, which make pandas function much like spreadsheet software. It also includes tools for much more complex computations than regular numpy allows

In [1]:
import pandas as pd
import numpy as np
# by default, pandas only shows the beginning and end of a large dataframe
# You can choose how many rows and columns to show.
# If you want to see all of the rows, set the respective value to None
pd.options.display.max_rows = 100 
pd.options.display.max_columns = 50

## Importing data
There are a lot of built-in functions for importing data to pandas, for example, from files, database, and web sources. For a full list of the supported methods, see [the documentation on pandas](https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html).

In this example, we're going to load data formatted as a csv from a website URL. In particular, it is a direct link to a file hosted in our course github repository.

The data we're loading is a simplified pokedex which includes the number, name, base stats, types, abilities, and colors of each pokemon. We'll be using this data to explore the functionality of pandas. 

The primary class of pandas is the DataFrame, which functions like a spreadsheet (like in excel). It allows for named rows and columns. Data types between two different columns can vary, but entries within the same column should have the same type.

In [2]:
# URL for data hosted online
pokedex_url = 'https://raw.githubusercontent.com/bwsi-remote-sensing-2023/01-Intro-to-python/master/pokedex.csv' 
pokedex_df = pd.read_csv(pokedex_url, index_col='Index') # create a dataframe from a csv, set the column titled "Index" as the row labels

In [3]:
# in our case, the cloned repository includes the pokedex file in the folder, 
# so we could equivalently use the filename instead of a URL
pokedex_df = pd.read_csv('pokedex.csv', index_col='Index')

In [4]:
# We'll do some cleanup to deal with empty values
pokedex_df = pokedex_df.fillna('') # fill in the NaN values with empty string 
pokedex_df # prints out the dataframe

,Pokemon,HP,Atk,Def,SpAtk,SpDef,Speed,Total,Type I,Type II,Ability I,Ability II,Hidden Ability,Color
Index,,,,,,,,,,,,,,
1.0,Bulbasaur,45,49,49,65,65,45,318,Grass,Poison,Overgrow,,Chlorophyll,Green
2.0,Ivysaur,60,62,63,80,80,60,405,Grass,Poison,Overgrow,,Chlorophyll,Green
3.0,Venusaur,80,82,83,100,100,80,525,Grass,Poison,Overgrow,,Chlorophyll,Green
4.0,Charmander,39,52,43,60,50,65,309,Fire,,Blaze,,Solar Power,Red
5.0,Charmeleon,58,64,58,80,65,80,405,Fire,,Blaze,,Solar Power,Red
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
798.0,Kartana,59,181,131,59,31,109,570,Grass,Steel,Beast Boost,,,White
799.0,Guzzlord,223,101,53,97,53,43,570,Dark,Dragon,Beast Boost,,,Black
800.0,Necrozma,97,107,101,127,89,79,600,Psychic,,Prism Armor,,,Black
801.0,Magearna,80,95,115,130,115,65,600,Steel,Fairy,Soul-Heart,,,Gray
802.0,Marshadow,90,125,80,90,90,125,600,Fighting,Ghost,Technician,,,Gray

## Indexing
Like numpy, you can index a dataframe to select elements or subsets of entries. There are a number of ways to index pandas dataframes. The two following methods are recommended:
`.loc[]` and `.iloc[]`

### .loc[ ] name-based indexing
The first way, using `.loc[a,b]` indexes based on the __values__ of the row index and column names. This allows us to get entries where the row index value equals `a` and the column name equals `b`.

In [5]:
# Get the entry for index value 745.1 - Lycanroc (midnight)
pokedex_df.loc[745.1]

Pokemon           Lycanroc (midnight)
HP                                 85
Atk                               115
Def                                75
SpAtk                              55
SpDef                              75
Speed                              82
Total                             487
Type I                           Rock
Type II
Ability I                    Keen Eye
Ability II              Vital Spirit
Hidden Ability               No Guard
Color                           Brown
Name: 745.1, dtype: object

In [6]:
# You can get specific column values for a single entry
pokedex_df.loc[250,['Pokemon','Type I','Type II']]

Pokemon    Swinub
Type I        Ice
Type II    Ground
Name: 250.0, dtype: object

In [7]:
# you can use the : notation to slice multiple rows and columns
pokedex_df.loc[690:700,'Pokemon':'Total']

          Pokemon   HP  Atk  Def  SpAtk  SpDef  Speed  Total
Index
690.0      Skrelp   50   60   60     60     60     30    320
691.0    Dragalge   65   75   90     97    123     44    494
692.0   Clauncher   50   53   62     58     63     44    330
693.0   Clawitzer   71   73   88    120     89     59    500
694.0  Helioptile   44   38   33     61     43     70    289
695.0   Heliolisk   62   55   52    109     94    109    481
696.0      Tyrunt   58   89   77     45     45     48    362
697.0   Tyrantrum   82  121  119     69     59     71    521
698.0      Amaura   77   59   50     67     63     46    362
699.0     Aurorus  123   77   72     99     92     58    521
700.0     Sylveon   95   65   65    110    130     60    525

In [8]:
# Similarly to numpy, you can use the : notation without indices on a side to mean "from beginning" or "to end"
pokedex_df.loc[:10,"Ability I":]

         Ability I Ability II Hidden Ability  Color
Index
1.0       Overgrow               Chlorophyll  Green
2.0       Overgrow               Chlorophyll  Green
3.0       Overgrow               Chlorophyll  Green
4.0          Blaze               Solar Power    Red
5.0          Blaze               Solar Power    Red
6.0          Blaze               Solar Power    Red
7.0        Torrent                 Rain Dish   Blue
8.0        Torrent                 Rain Dish   Blue
9.0        Torrent                 Rain Dish   Blue
10.0   Shield Dust                  Run Away  Green

In [9]:
# and : by itself gives all of the entries in that dimension
pokedex_df.loc[:,'Pokemon'].head(10) #just return top 10 entries

Index
1.0      Bulbasaur
2.0        Ivysaur
3.0       Venusaur
4.0     Charmander
5.0     Charmeleon
6.0      Charizard
7.0       Squirtle
8.0      Wartortle
9.0      Blastoise
10.0      Caterpie
Name: Pokemon, dtype: object

### .iloc[ ] integer indexing

The second way, using `.iloc[i,j]` uses the numpy-style integer indices to get a value. In this case, iloc takes integer values from 0 to the number of entries in that dimension. 

Like numpy, `.iloc[i,j]` gives the entry at the $i^{th}$ row and $j^{th}$ column.

In [10]:
pokedex_df.iloc[100] # gets 101st row (recall python counts from 0)

Pokemon            Electrode
HP                        60
Atk                       50
Def                       70
SpAtk                     80
SpDef                     80
Speed                    140
Total                    480
Type I              Electric
Type II
Ability I         Soundproof
Ability II            Static
Hidden Ability     Aftermath
Color                    Red
Name: 110.0, dtype: object

In [11]:
# The : style indexing also works for iloc
pokedex_df.iloc[25:30, 0:8]

         Pokemon  HP  Atk  Def  SpAtk  SpDef  Speed  Total
Index
27.0      Raichu  60   90   55     90     80    100    475
28.0   Sandshrew  50   75   85     20     30     40    300
29.0   Sandslash  75  100  110     45     55     65    450
30.0    Nidoran♀  55   47   52     40     40     41    275
31.0    Nidorina  70   62   67     55     55     56    365

## Changing index column
You can change the index column of the dataframe with `.set_index()` or reset it to default numerical indexing with `.reset_index()`.

Note however, that these operations create a __copy__ of the original dataframe, and do not change the dataframe "in place" (i.e. doesn't change the original object)

In [12]:
# reset index to be default numerical index
reindexed_pokedex = pokedex_df.reset_index()
reindexed_pokedex.head()

,Index,Pokemon,HP,Atk,Def,SpAtk,SpDef,Speed,Total,Type I,Type II,Ability I,Ability II,Hidden Ability,Color
0,1.0,Bulbasaur,45,49,49,65,65,45,318,Grass,Poison,Overgrow,,Chlorophyll,Green
1,2.0,Ivysaur,60,62,63,80,80,60,405,Grass,Poison,Overgrow,,Chlorophyll,Green
2,3.0,Venusaur,80,82,83,100,100,80,525,Grass,Poison,Overgrow,,Chlorophyll,Green
3,4.0,Charmander,39,52,43,60,50,65,309,Fire,,Blaze,,Solar Power,Red
4,5.0,Charmeleon,58,64,58,80,65,80,405,Fire,,Blaze,,Solar Power,Red

In [13]:
# Change the index to the Pokemon name column
pokedex_indexed_by_name = pokedex_df.reset_index().set_index('Pokemon')
pokedex_indexed_by_name

,Index,HP,Atk,Def,SpAtk,SpDef,Speed,Total,Type I,Type II,Ability I,Ability II,Hidden Ability,Color
Pokemon,,,,,,,,,,,,,,
Bulbasaur,1.0,45,49,49,65,65,45,318,Grass,Poison,Overgrow,,Chlorophyll,Green
Ivysaur,2.0,60,62,63,80,80,60,405,Grass,Poison,Overgrow,,Chlorophyll,Green
Venusaur,3.0,80,82,83,100,100,80,525,Grass,Poison,Overgrow,,Chlorophyll,Green
Charmander,4.0,39,52,43,60,50,65,309,Fire,,Blaze,,Solar Power,Red
Charmeleon,5.0,58,64,58,80,65,80,405,Fire,,Blaze,,Solar Power,Red
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Kartana,798.0,59,181,131,59,31,109,570,Grass,Steel,Beast Boost,,,White
Guzzlord,799.0,223,101,53,97,53,43,570,Dark,Dragon,Beast Boost,,,Black
Necrozma,800.0,97,107,101,127,89,79,600,Psychic,,Prism Armor,,,Black
Magearna,801.0,80,95,115,130,115,65,600,Steel,Fairy,Soul-Heart,,,Gray
Marshadow,802.0,90,125,80,90,90,125,600,Fighting,Ghost,Technician,,,Gray

In [14]:
# note that the original dataframe was not affected
pokedex_df

,Pokemon,HP,Atk,Def,SpAtk,SpDef,Speed,Total,Type I,Type II,Ability I,Ability II,Hidden Ability,Color
Index,,,,,,,,,,,,,,
1.0,Bulbasaur,45,49,49,65,65,45,318,Grass,Poison,Overgrow,,Chlorophyll,Green
2.0,Ivysaur,60,62,63,80,80,60,405,Grass,Poison,Overgrow,,Chlorophyll,Green
3.0,Venusaur,80,82,83,100,100,80,525,Grass,Poison,Overgrow,,Chlorophyll,Green
4.0,Charmander,39,52,43,60,50,65,309,Fire,,Blaze,,Solar Power,Red
5.0,Charmeleon,58,64,58,80,65,80,405,Fire,,Blaze,,Solar Power,Red
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
798.0,Kartana,59,181,131,59,31,109,570,Grass,Steel,Beast Boost,,,White
799.0,Guzzlord,223,101,53,97,53,43,570,Dark,Dragon,Beast Boost,,,Black
800.0,Necrozma,97,107,101,127,89,79,600,Psychic,,Prism Armor,,,Black
801.0,Magearna,80,95,115,130,115,65,600,Steel,Fairy,Soul-Heart,,,Gray
802.0,Marshadow,90,125,80,90,90,125,600,Fighting,Ghost,Technician,,,Gray

## Logical indexing
You can test conditionals on a column, for example, testing if the value of the column is greater than a value. What's returned is a boolean column of the same size, with a value of `True` wherever it is true, and `False` otherwise. (This can similarly be done in numpy).

In [15]:
pokedex_df['Total'] > 520

Index
1.0      False
2.0      False
3.0       True
4.0      False
5.0      False
         ...
798.0     True
799.0     True
800.0     True
801.0     True
802.0     True
Name: Total, Length: 820, dtype: bool

If you take that boolean column and use it to index the dataframe, you can get all of the entries that satisfy that condition.

In [16]:
pokedex_df.loc[pokedex_df['Total']>=520] # all of the pokemon with total base stats greater than 500

,Pokemon,HP,Atk,Def,SpAtk,SpDef,Speed,Total,Type I,Type II,Ability I,Ability II,Hidden Ability,Color
Index,,,,,,,,,,,,,,
3.0,Venusaur,80,82,83,100,100,80,525,Grass,Poison,Overgrow,,Chlorophyll,Green
6.0,Charizard,78,84,78,109,85,100,534,Fire,Flying,Blaze,,Solar Power,Red
9.0,Blastoise,79,83,100,85,105,78,530,Water,,Torrent,,Rain Dish,Blue
64.0,Arcanine,90,110,80,100,80,95,555,Fire,,Intimidate,Flash Fire,Justified,Brown
99.0,Cloyster,50,90,180,85,45,70,520,Water,Ice,Shell Armor,Skill Link,Overcoat,Purple
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
798.0,Kartana,59,181,131,59,31,109,570,Grass,Steel,Beast Boost,,,White
799.0,Guzzlord,223,101,53,97,53,43,570,Dark,Dragon,Beast Boost,,,Black
800.0,Necrozma,97,107,101,127,89,79,600,Psychic,,Prism Armor,,,Black
801.0,Magearna,80,95,115,130,115,65,600,Steel,Fairy,Soul-Heart,,,Gray
802.0,Marshadow,90,125,80,90,90,125,600,Fighting,Ghost,Technician,,,Gray

In [17]:
# Get all of the pokemon of a given color
pokedex_df.loc[pokedex_df['Color']=='Black']

,Pokemon,HP,Atk,Def,SpAtk,SpDef,Speed,Total,Type I,Type II,Ability I,Ability II,Hidden Ability,Color
Index,,,,,,,,,,,,,,
174.0,Snorlax,160,110,65,65,110,30,540,Normal,,Immunity,Thick Fat,Gluttony,Black
162.0,Umbreon,95,65,110,60,130,65,525,Dark,,Synchronize,,Inner Focus,Black
226.0,Murkrow,60,85,42,85,42,91,405,Dark,Flying,Insomnia,Super Luck,Prankster,Black
230.0,Unown,48,72,48,72,48,48,336,Psychic,,Levitate,,,Black
244.0,Sneasel,55,95,55,35,75,115,430,Dark,Ice,Inner Focus,Keen Eye,Pickpocket,Black
260.0,Houndour,45,60,30,80,50,65,330,Dark,Fire,Early Bird,Flash Fire,Unnerve,Black
261.0,Houndoom,75,90,50,110,80,95,500,Dark,Fire,Early Bird,Flash Fire,Unnerve,Black
328.0,Mawile,50,85,85,55,55,50,380,Steel,Fairy,Hyper Cutter,Intimidate,Sheer Force,Black
352.0,Spoink,60,25,35,70,80,60,330,Psychic,,Thick Fat,Own Tempo,Gluttony,Black
363.0,Seviper,73,100,60,100,60,65,458,Poison,,Shed Skin,,Infiltrator,Black
371.0,Claydol,60,70,105,70,120,75,500,Ground,Psychic,Levitate,,,Black
380.0,Shuppet,44,75,35,63,33,45,295,Ghost,,Insomnia,Frisk,Cursed Body,Black
381.0,Banette,64,115,65,83,63,65,455,Ghost,,Insomnia,Frisk,Cursed Body,Black
382.0,Duskull,20,40,90,30,90,25,295,Ghost,,Levitate,,,Black
383.0,Dusclops,40,70,130,60,130,25,455,Ghost,,Pressure,,,Black
227.0,Honchkrow,100,125,52,105,52,71,505,Dark,Flying,Insomnia,Super Luck,Moxie,Black
461.0,Chatot,76,65,45,92,42,91,411,Normal,Flying,Keen Eye,Tangled Feet,Big Pecks,Black
173.0,Munchlax,135,85,40,40,85,5,390,Normal,,Pickup,Thick Fat,Gluttony,Black
245.0,Weavile,70,120,65,45,85,125,510,Dark,Ice,Pressure,,Pickpocket,Black
384.0,Dusknoir,45,100,135,65,135,45,525,Ghost,,Pressure,,,Black
487.0,Giratina,150,100,120,100,120,90,680,Ghost,Dragon,Pressure,,Telepathy,Black
487.1,Giratina (O),150,120,100,120,100,90,680,Ghost,Dragon,Levitate,,,Black
491.0,Darkrai,70,90,90,135,90,125,600,Dark,,Bad Dreams,,,Black
522.0,Blitzle,45,60,32,50,32,76,295,Electric,,Lightningrod,Motor Drive,Sap Sipper,Black
523.0,Zebstrika,75,100,63,80,63,116,497,Electric,,Lightningrod,Motor Drive,Sap Sipper,Black
561.0,Sigilyph,72,58,80,103,80,97,490,Psychic,Flying,Wonder Skin,Magic Guard,Tinted Lens,Black
562.0,Yamask,38,30,85,55,65,30,303,Ghost,,Mummy,,,Black
608.0,Lampent,60,40,60,95,60,55,370,Ghost,Fire,Flash Fire,Flame Body,Shadow Tag,Black
609.0,Chandelure,60,55,90,145,90,80,520,Ghost,Fire,Flash Fire,Flame Body,Shadow Tag,Black
644.0,Zekrom,100,150,120,120,100,90,680,Dragon,Electric,Teravolt,,,Black
664.0,Scatterbug,38,35,40,27,25,35,200,Bug,,Shield Dust,Compound Eyes,Friend Guard,Black
665.0,Spewpa,45,22,60,27,30,29,213,Bug,,Shed Skin,,Friend Guard,Black
666.0,Vivillon,80,52,50,90,50,89,411,Bug,Flying,Shield Dust,Compound Eyes,Friend Guard,Black
731.0,Pikipek,35,75,30,30,30,65,265,Normal,Flying,Keen Eye,Skill Link,Pickup,Black
732.0,Trumbeak,55,85,50,40,50,75,355,Normal,Flying,Keen Eye,Skill Link,Pickup,Black
733.0,Toucannon,80,120,75,75,75,60,485,Normal,Flying,Keen Eye,Skill Link,Sheer Force,Black
757.0,Salandit,48,44,40,71,40,77,320,Poison,Fire,Corrosion,Oblivious,Oblivious,Black
758.0,Salazzle,68,64,60,111,60,117,480,Poison,Fire,Corrosion,Oblivious,Oblivious,Black
771.0,Pyukumuku,55,60,130,30,130,5,410,Water,,Innards Out,Unaware,Unaware,Black
796.0,Xurkitree,83,89,71,173,71,83,570,Electric,,Beast Boost,,,Black
799.0,Guzzlord,223,101,53,97,53,43,570,Dark,Dragon,Beast Boost,,,Black
800.0,Necrozma,97,107,101,127,89,79,600,Psychic,,Prism Armor,,,Black

### Compound boolean queries
You can use boolean operations (OR, AND, NOT) to combine conditions

We will look for pokemon with specific types to demonstrate compound queries

### OR queries
In the following example, we query for all pokemon who have at least part "Dragon" typing.

The vertical line | represents the element-wise "OR" operation. "OR" operations require either or both statements on either side of the operation to be true.

Thus, the below query 

```query = (pokedex_df['Type I']=='Dragon') | (pokedex_df['Type II']=='Dragon')```

asks, for each row, if 'Type I' is equal to "Dragon" OR 'Type II' is equal to "Dragon"

In [18]:
query = (pokedex_df['Type I']=='Dragon') | (pokedex_df['Type II']=='Dragon')
pokedex_df.loc[query] # Get all of the entries corresponding to the above query

,Pokemon,HP,Atk,Def,SpAtk,SpDef,Speed,Total,Type I,Type II,Ability I,Ability II,Hidden Ability,Color
Index,,,,,,,,,,,,,,
178.0,Dratini,41,64,45,50,50,50,300,Dragon,,Shed Skin,,Marvel Scale,Blue
179.0,Dragonair,61,84,65,70,70,70,420,Dragon,,Shed Skin,,Marvel Scale,Blue
180.0,Dragonite,91,134,95,100,100,80,600,Dragon,Flying,Inner Focus,,Multiscale,Brown
134.0,Kingdra,75,95,95,95,95,85,540,Water,Dragon,Swift Swim,Sniper,Damp,Blue
356.0,Vibrava,50,70,50,50,50,70,340,Ground,Dragon,Levitate,,,Green
357.0,Flygon,80,100,80,80,80,100,520,Ground,Dragon,Levitate,,,Green
361.0,Altaria,75,70,90,70,105,80,490,Dragon,Flying,Natural Cure,,Cloud Nine,Blue
400.0,Bagon,45,75,60,40,30,50,300,Dragon,,Rock Head,,Sheer Force,Blue
401.0,Shelgon,65,95,100,60,50,50,420,Dragon,,Rock Head,,Overcoat,White
402.0,Salamence,95,135,80,110,80,100,600,Dragon,Flying,Intimidate,,Moxie,Blue
409.0,Latias,80,80,90,110,130,110,600,Dragon,Psychic,Levitate,,,Red
410.0,Latios,80,90,80,130,110,110,600,Dragon,Psychic,Levitate,,,Blue
413.0,Rayquaza,105,150,90,150,90,95,680,Dragon,Flying,Air Lock,,,Green
463.0,Gible,58,70,45,40,45,42,300,Dragon,Ground,Sand Veil,,Rough Skin,Blue
464.0,Gabite,68,90,65,50,55,82,410,Dragon,Ground,Sand Veil,,Rough Skin,Blue
465.0,Garchomp,108,130,95,80,85,102,600,Dragon,Ground,Sand Veil,,Rough Skin,Blue
483.0,Dialga,100,120,120,150,100,90,680,Steel,Dragon,Pressure,,Telepathy,White
484.0,Palkia,90,120,100,150,120,100,680,Water,Dragon,Pressure,,Telepathy,Purple
487.0,Giratina,150,100,120,100,120,90,680,Ghost,Dragon,Pressure,,Telepathy,Black
487.1,Giratina (O),150,120,100,120,100,90,680,Ghost,Dragon,Levitate,,,Black
610.0,Axew,46,87,60,30,40,57,320,Dragon,,Rivalry,Mold Breaker,Unnerve,Green
611.0,Fraxure,66,117,70,40,50,67,410,Dragon,,Rivalry,Mold Breaker,Unnerve,Green
612.0,Haxorus,76,147,90,60,70,97,540,Dragon,,Rivalry,Mold Breaker,Unnerve,Yellow
621.0,Druddigon,77,120,90,60,90,48,485,Dragon,,Rough Skin,Sheer Force,Mold Breaker,Red
633.0,Deino,52,65,50,45,50,38,300,Dark,Dragon,Hustle,,,Blue
634.0,Zweilous,72,85,70,65,70,58,420,Dark,Dragon,Hustle,,,Blue
635.0,Hydreigon,92,105,90,125,90,98,600,Dark,Dragon,Levitate,,,Blue
643.0,Reshiram,100,120,100,150,120,90,680,Dragon,Fire,Turboblaze,,,White
644.0,Zekrom,100,150,120,120,100,90,680,Dragon,Electric,Teravolt,,,Black
646.0,Kyurem,125,130,90,130,90,95,660,Dragon,Ice,Pressure,,,Gray
691.0,Dragalge,65,75,90,97,123,44,494,Poison,Dragon,Poison Point,Poison Touch,Adaptability,Brown
696.0,Tyrunt,58,89,77,45,45,48,362,Rock,Dragon,Strong Jaw,,Sturdy,Brown
697.0,Tyrantrum,82,121,119,69,59,71,521,Rock,Dragon,Strong Jaw,,Sturdy,Red
704.0,Goomy,45,50,35,55,75,40,300,Dragon,,Sap Sipper,Hydration,Gooey,Purple
705.0,Sliggoo,68,75,53,83,113,60,452,Dragon,,Sap Sipper,Hydration,Gooey,Purple
706.0,Goodra,90,100,70,110,150,80,600,Dragon,,Sap Sipper,Hydration,Gooey,Purple
714.0,Noibat,40,30,35,45,40,55,245,Flying,Dragon,Frisk,Infiltrator,Telepathy,Purple
715.0,Noivern,85,70,80,97,80,123,535,Flying,Dragon,Frisk,Infiltrator,Telepathy,Purple
718.0,Zygarde,108,100,121,81,95,95,600,Dragon,Ground,Aura Break,,,Green
776.0,Turtonator,60,78,135,91,85,36,485,Fire,Dragon,Shell Armor,,,Red
780.0,Drampa,78,60,85,135,91,36,485,Normal,Dragon,Berserk,Sap Sipper,Cloud Nine,White
782.0,Jangmo-o,45,55,65,45,45,45,300,Dragon,,Bulletproof,Soundproof,Overcoat,Gray
783.0,Hakamo-o,55,75,90,65,70,65,420,Dragon,Fighting,Bulletproof,Soundproof,Overcoat,Gray
784.0,Kommo-o,75,110,125,100,105,85,600,Dragon,Fighting,Bulletproof,Soundproof,Overcoat,Gray
799.0,Guzzlord,223,101,53,97,53,43,570,Dark,Dragon,Beast Boost,,,Black

In [19]:
(pokedex_df['Type I']=='Dragon').all()

False

### AND queries
The ampersand `&` character represents the element-wise boolean operation "AND". In order for an "AND" statement to be true, both conditions on either side of the operation must be true.

We can combine boolean operations to construct complex queries: for example, getting all pokemon who are both Dragon and Flying types. The query below looks for pokemon who are EITHER (Primary Type "Flying" AND Secondary Type "Dragon") OR (Primary Type "Dragon" AND Secondary Type "Flying")

Note that parentheses should be used to group operations so that the order of operations is clear

In [20]:
# you can use the backslash operator \ to continue code on the next line
query = ((pokedex_df['Type I']=='Flying') & (pokedex_df['Type II']=='Dragon'))\
        | ((pokedex_df['Type I']=='Dragon') & (pokedex_df['Type II']=='Flying'))
pokedex_df.loc[query]

,Pokemon,HP,Atk,Def,SpAtk,SpDef,Speed,Total,Type I,Type II,Ability I,Ability II,Hidden Ability,Color
Index,,,,,,,,,,,,,,
180.0,Dragonite,91,134,95,100,100,80,600,Dragon,Flying,Inner Focus,,Multiscale,Brown
361.0,Altaria,75,70,90,70,105,80,490,Dragon,Flying,Natural Cure,,Cloud Nine,Blue
402.0,Salamence,95,135,80,110,80,100,600,Dragon,Flying,Intimidate,,Moxie,Blue
413.0,Rayquaza,105,150,90,150,90,95,680,Dragon,Flying,Air Lock,,,Green
714.0,Noibat,40,30,35,45,40,55,245,Flying,Dragon,Frisk,Infiltrator,Telepathy,Purple
715.0,Noivern,85,70,80,97,80,123,535,Flying,Dragon,Frisk,Infiltrator,Telepathy,Purple

### NOT queries
There are two ways to do negation. Consider the following query for selecting all pokemon who are Fire type, but not Flying

```
query = ((pokedex_df['Type I']=='Fire') & ~(pokedex_df['Type II']=='Flying'))\
        | ((pokedex_df['Type I']!='Flying') & (pokedex_df['Type II']=='Fire'))
```

The first way to do negation is with the tilde ~ symbol, which negates the subsequent boolean statement:
We use this in `~(pokedex_df['Type II']=='Flying')`.
The parentheses determine order of operations. First we find all entries where their secondary type is "Flying"
Then the tilde in front negates that statement, flipping all True values to False, and vice versa

The second way to do negation is using the != notation, which represents "not equal to"
We use this in `(pokedex_df['Type I']!='Flying')`
This finds all entries where their primary type is not equal to "Flying"

In [21]:
query = ((pokedex_df['Type I']=='Fire') & ~(pokedex_df['Type II']=='Flying'))\
        | ((pokedex_df['Type I']!='Flying') & (pokedex_df['Type II']=='Fire'))

pokedex_df.loc[query]

,Pokemon,HP,Atk,Def,SpAtk,SpDef,Speed,Total,Type I,Type II,Ability I,Ability II,Hidden Ability,Color
Index,,,,,,,,,,,,,,
4.0,Charmander,39,52,43,60,50,65,309,Fire,,Blaze,,Solar Power,Red
5.0,Charmeleon,58,64,58,80,65,80,405,Fire,,Blaze,,Solar Power,Red
39.0,Vulpix,38,41,40,50,65,65,299,Fire,,Flash Fire,,Drought,Brown
40.0,Ninetales,73,76,75,81,100,100,505,Fire,,Flash Fire,,Drought,Yellow
63.0,Growlithe,55,70,45,70,50,60,350,Fire,,Intimidate,Flash Fire,Justified,Brown
64.0,Arcanine,90,110,80,100,80,95,555,Fire,,Intimidate,Flash Fire,Justified,Brown
83.0,Ponyta,50,85,55,65,65,90,410,Fire,,Run Away,Flash Fire,Flame Body,Yellow
84.0,Rapidash,65,100,70,80,80,105,500,Fire,,Run Away,Flash Fire,Flame Body,Yellow
149.0,Magmar,65,95,57,100,85,93,495,Fire,,Flame Body,,Vital Spirit,Red
160.0,Flareon,65,130,60,95,110,65,525,Fire,,Flash Fire,,Guts,Red
186.0,Cyndaquil,39,52,43,60,50,65,309,Fire,,Blaze,,Flash Fire,Yellow
187.0,Quilava,58,64,58,80,65,80,405,Fire,,Blaze,,Flash Fire,Yellow
188.0,Typhlosion,78,84,78,109,85,100,534,Fire,,Blaze,,Flash Fire,Yellow
248.0,Slugma,40,40,40,70,40,20,250,Fire,,Magma Armor,Flame Body,Weak Armor,Red
249.0,Magcargo,50,50,120,80,80,30,410,Fire,Rock,Magma Armor,Flame Body,Weak Armor,Red
260.0,Houndour,45,60,30,80,50,65,330,Dark,Fire,Early Bird,Flash Fire,Unnerve,Black
261.0,Houndoom,75,90,50,110,80,95,500,Dark,Fire,Early Bird,Flash Fire,Unnerve,Black
148.0,Magby,45,75,37,70,55,83,365,Fire,,Flame Body,,Vital Spirit,Red
268.0,Entei,115,115,85,90,75,100,580,Fire,,Pressure,,Flash Fire,Brown
279.0,Torchic,45,60,40,70,50,45,310,Fire,,Blaze,,Speed Boost,Red
280.0,Combusken,60,85,60,85,60,55,405,Fire,Fighting,Blaze,,Speed Boost,Red
281.0,Blaziken,80,120,70,110,70,80,530,Fire,Fighting,Blaze,,Speed Boost,Red
349.0,Numel,60,60,40,65,45,35,305,Fire,Ground,Oblivious,Simple,Own Tempo,Yellow
350.0,Camerupt,70,100,70,105,75,40,460,Fire,Ground,Magma Armor,Solid Rock,Anger Point,Red
351.0,Torkoal,70,85,140,85,70,20,470,Fire,,White Smoke,,Shell Armor,Brown
419.0,Chimchar,44,58,44,58,44,61,309,Fire,,Blaze,,Iron Fist,Brown
420.0,Monferno,64,78,52,78,52,81,405,Fire,Fighting,Blaze,,Iron Fist,Brown
421.0,Infernape,76,104,71,104,71,108,534,Fire,Fighting,Blaze,,Iron Fist,Brown
150.0,Magmortar,75,95,67,125,95,83,540,Fire,,Flame Body,,Vital Spirit,Red
479.1,Rotom (Heat),50,65,107,105,107,86,520,Electric,Fire,Levitate,,,Red
485.0,Heatran,91,90,106,130,106,77,600,Fire,Steel,Flash Fire,,Flame Body,Brown
494.0,Victini,100,100,100,100,100,100,600,Psychic,Fire,Victory Star,,,Yellow
498.0,Tepig,65,63,45,45,45,45,308,Fire,,Blaze,,Thick Fat,Red
499.0,Pignite,90,93,55,70,55,55,418,Fire,Fighting,Blaze,,Thick Fat,Red
500.0,Emboar,110,123,65,100,65,65,528,Fire,Fighting,Blaze,,Reckless,Red
513.0,Pansear,50,53,48,53,48,64,316,Fire,,Gluttony,,Blaze,Red
514.0,Simisear,75,98,63,98,63,101,498,Fire,,Gluttony,,Blaze,Red
554.0,Darumaka,70,90,45,15,45,50,315,Fire,,Hustle,,Inner Focus,Red
555.0,Darmanitan,105,140,55,30,55,95,480,Fire,,Sheer Force,,Zen Mode,Red
555.1,Darmanitan (Z),105,30,105,140,105,55,540,Fire,Psychic,,,Zen Mode,Red
607.0,Litwick,50,30,55,65,55,20,275,Ghost,Fire,Flash Fire,Flame Body,Shadow Tag,White
608.0,Lampent,60,40,60,95,60,55,370,Ghost,Fire,Flash Fire,Flame Body,Shadow Tag,Black
609.0,Chandelure,60,55,90,145,90,80,520,Ghost,Fire,Flash Fire,Flame Body,Shadow Tag,Black
631.0,Heatmor,85,97,66,105,66,65,484,Fire,,Gluttony,Flash Fire,White Smoke,Red
636.0,Larvesta,55,85,55,50,55,60,360,Bug,Fire,Flame Body,,Swarm,White
637.0,Volcarona,85,60,65,135,105,100,550,Bug,Fire,Flame Body,,Swarm,White
643.0,Reshiram,100,120,100,150,120,90,680,Dragon,Fire,Turboblaze,,,White
653.0,Fennekin,40,45,40,62,60,60,307,Fire,,Blaze,,Magician,Red
654.0,Braixen,59,59,58,90,70,73,409,Fire,,Blaze,,Magician,Red
655.0,Delphox,75,69,72,114,100,104,534,Fire,Psychic,Blaze,,Magician,Red
667.0,Litleo,62,50,58,73,54,72,369,Fire,Normal,Rivalry,Unnerve,Moxie,Brown
668.0,Pyroar,86,68,72,109,66,106,507,Fire,Normal,Rivalry,Unnerve,Moxie,Brown
721.0,Volcanion,80,110,120,130,90,70,600,Fire,Water,Water Absorb,,,Brown
725.0,Litten,45,65,40,60,40,70,320,Fire,,Blaze,Intimidate,,Red
726.0,Torracat,65,85,50,80,50,90,420,Fire,,Blaze,Intimidate,,Red
727.0,Incineroar,95,115,90,80,90,60,530,Fire,Dark,Blaze,Intimidate,,Red
757.0,Salandit,48,44,40,71,40,77,320,Poison,Fire,Corrosion,Oblivious,Oblivious,Black
758.0,Salazzle,68,64,60,111,60,117,480,Poison,Fire,Corrosion,Oblivious,Oblivious,Black
776.0,Turtonator,60,78,135,91,85,36,485,Fire,Dragon,Shell Armor,,,Red

## Sorting
Dataframes can be sorted by value

In [22]:
pokedex_df.sort_values('Pokemon', ascending=False) # Sort by name descending

,Pokemon,HP,Atk,Def,SpAtk,SpDef,Speed,Total,Type I,Type II,Ability I,Ability II,Hidden Ability,Color
Index,,,,,,,,,,,,,,
718.0,Zygarde,108,100,121,81,95,95,600,Dragon,Ground,Aura Break,,,Green
634.0,Zweilous,72,85,70,65,70,58,420,Dark,Dragon,Hustle,,,Blue
44.0,Zubat,40,45,35,30,40,55,245,Poison,Flying,Inner Focus,,Infiltrator,Purple
570.0,Zorua,40,65,40,80,40,65,330,Dark,,Illusion,,,Gray
571.0,Zoroark,60,105,60,120,60,105,510,Dark,,Illusion,,,Gray
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
681.0,Aegislash,60,50,150,50,150,60,520,Steel,Ghost,Stance Change,,,Brown
617.0,Accelgor,80,70,40,100,60,145,495,Bug,,Hydration,Sticky Hold,Unburden,Red
388.0,Absol,65,130,60,75,60,75,465,Dark,,Pressure,Super Luck,Justified,White
69.0,Abra,25,20,15,105,55,90,310,Psychic,,Synchronize,Inner Focus,Magic Guard,Brown
478.0,Abomasnow,90,92,75,92,85,60,494,Ice,Grass,Snow Warning,,Soundproof,White

In [23]:
# You can sort by multiple columns
pokedex_df.sort_values(['Type I','Type II', 'Total'], ascending=False) # Sort by type combination, then stats descending

,Pokemon,HP,Atk,Def,SpAtk,SpDef,Speed,Total,Type I,Type II,Ability I,Ability II,Hidden Ability,Color
Index,,,,,,,,,,,,,,
424.0,Empoleon,84,86,88,111,101,60,530,Water,Steel,Torrent,,Defiant,Blue
565.0,Carracosta,74,108,133,83,65,32,495,Water,Rock,Solid Rock,Sturdy,Swift Swim,Blue
398.0,Relicanth,100,90,130,45,65,55,485,Water,Rock,Swift Swim,Rock Head,Sturdy,Gray
253.0,Corsola,55,55,85,65,85,35,380,Water,Rock,Hustle,Natural Cure,Regenerator,Pink
564.0,Tirtouga,54,78,103,53,45,22,355,Water,Rock,Solid Rock,Sturdy,Swift Swim,Blue
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
292.0,Cascoon,50,35,55,25,25,15,205,Bug,,Shed Skin,,,Purple
664.0,Scatterbug,38,35,40,27,25,35,200,Bug,,Shield Dust,Compound Eyes,Friend Guard,Black
10.0,Caterpie,45,30,35,20,20,45,195,Bug,,Shield Dust,,Run Away,Green
289.0,Wurmple,45,45,35,20,30,20,195,Bug,,Shield Dust,,Run Away,Red
430.0,Kricketot,37,25,41,25,41,25,194,Bug,,Shed Skin,,Run Away,Red

## Adding columns, rows, and changing values
You can add another column like:
```
dataframe['NewColumnName'] = value
```
`value` can be a single value, an array of the same size as the index of `dataframe`, a pandas `Series`, or a dictionary mapping `index: value` for entries in the dataframe index

In [24]:
pokedex_df['Nickname'] = None
pokedex_df

,Pokemon,HP,Atk,Def,SpAtk,SpDef,Speed,Total,Type I,Type II,Ability I,Ability II,Hidden Ability,Color,Nickname
Index,,,,,,,,,,,,,,,
1.0,Bulbasaur,45,49,49,65,65,45,318,Grass,Poison,Overgrow,,Chlorophyll,Green,None
2.0,Ivysaur,60,62,63,80,80,60,405,Grass,Poison,Overgrow,,Chlorophyll,Green,None
3.0,Venusaur,80,82,83,100,100,80,525,Grass,Poison,Overgrow,,Chlorophyll,Green,None
4.0,Charmander,39,52,43,60,50,65,309,Fire,,Blaze,,Solar Power,Red,None
5.0,Charmeleon,58,64,58,80,65,80,405,Fire,,Blaze,,Solar Power,Red,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
798.0,Kartana,59,181,131,59,31,109,570,Grass,Steel,Beast Boost,,,White,None
799.0,Guzzlord,223,101,53,97,53,43,570,Dark,Dragon,Beast Boost,,,Black,None
800.0,Necrozma,97,107,101,127,89,79,600,Psychic,,Prism Armor,,,Black,None
801.0,Magearna,80,95,115,130,115,65,600,Steel,Fairy,Soul-Heart,,,Gray,None
802.0,Marshadow,90,125,80,90,90,125,600,Fighting,Ghost,Technician,,,Gray,None

In [25]:
# you can change the value of an entry using indexing and assignment =
pokedex_df.loc[4,'Nickname'] = 'Abby' # indexing using .loc[] pokedex entry 4, 'Nickname column'
pokedex_df.iloc[113,-1] = 'Terry' # indexing using .iloc[] 113rd row, last column
pokedex_df.iloc[[3,113],:]

,Pokemon,HP,Atk,Def,SpAtk,SpDef,Speed,Total,Type I,Type II,Ability I,Ability II,Hidden Ability,Color,Nickname
Index,,,,,,,,,,,,,,,
4.0,Charmander,39,52,43,60,50,65,309,Fire,,Blaze,,Solar Power,Red,Abby
129.0,Tangela,65,55,115,100,40,60,435,Grass,,Chlorophyll,Leaf Guard,Regenerator,Blue,Terry

## Combining Dataframes
### Appending

Some of you may have noticed that the pokedex file only includes Generations 1-7 of pokemon. Let's add the pokemon from Gen 8. The file `pokedex_gen8.csv` contains the pokedex entries for all of the pokemon that show up in the 8th generation of games (Sword/Shield).

In [26]:
# you can add another dataframe on to the end using append()
gen8_pokedex_df = pd.read_csv('pokedex_gen8.csv') # create a dataframe with new entries

In [27]:
appended_pokedex_df = pd.concat([pokedex_df, gen8_pokedex_df], ignore_index=True, sort=False) # the sort=False keyword prevents the columns from being reordered alphabetically
appended_pokedex_df = appended_pokedex_df.fillna('').drop_duplicates() # some cleanup operations, replace NaN with emptry strings, and drop duplicate rows
appended_pokedex_df

,Pokemon,HP,Atk,Def,SpAtk,SpDef,Speed,Total,Type I,Type II,Ability I,Ability II,Hidden Ability,Color,Nickname,Galar Pokedex Number,Weight_kg,Height_m,Weight_lbs,Height_ft,Cap_Rate,Egg_Steps,Classification
0,Bulbasaur,45,49,49,65,65,45,318.0,Grass,Poison,Overgrow,,Chlorophyll,Green,,,,,,,,,
1,Ivysaur,60,62,63,80,80,60,405.0,Grass,Poison,Overgrow,,Chlorophyll,Green,,,,,,,,,
2,Venusaur,80,82,83,100,100,80,525.0,Grass,Poison,Overgrow,,Chlorophyll,Green,,,,,,,,,
3,Charmander,39,52,43,60,50,65,309.0,Fire,,Blaze,,Solar Power,Red,Abby,,,,,,,,
4,Charmeleon,58,64,58,80,65,80,405.0,Fire,,Blaze,,Solar Power,Red,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1215,Drakloak,68,80,50,60,50,102,,dragon,ghost,Clear Body,Infiltrator,Cursed Body,,,396.0,11.0,1.4,24.3,4.583,45.0,10240.0,Caretaker Pokémon
1216,Dragapult,88,120,75,100,75,142,,dragon,ghost,Clear Body,Infiltrator,Cursed Body,,,397.0,50.0,3.0,110.2,9.833,45.0,10240.0,Stealth Pokémon
1217,Zacian,92,130,115,80,115,138,,fairy,,Intrepid Sword,,,,,398.0,110.0,2.8,242.5,9.167,10.0,30720.0,Warrior Pokémon
1218,Zamazenta,92,130,115,80,115,138,,fighting,,Dauntless Shield,,,,,399.0,210.0,2.9,463.0,9.5,10.0,30720.0,Warrior Pokémon
1219,Eternatus,140,85,95,145,95,130,,poison,dragon,Pressure,,,,,400.0,950.0,20.0,2094.4,65.583,255.0,30720.0,Gigantic Pokémon

However, you may notice that some pokemon show up twice in the combined dataframe, and since the entries in `gen8_pokedex_df` includes different columns, `remove_duplicates` does not see those entries as duplicates.

To remedy this, we can index both dataframes by the name of the pokemon and use the [`combine_first`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.combine_first.html#pandas.DataFrame.combine_first) function to fill in the null values of one dataframe with the corresponding values in the other.

In [28]:
gen8_pokedex_indexed_by_name = gen8_pokedex_df.reset_index().set_index('Pokemon')
combined_pokedex_df = pokedex_indexed_by_name.combine_first(gen8_pokedex_indexed_by_name)
combined_pokedex_df

,Ability I,Ability II,Atk,Cap_Rate,Classification,Color,Def,Egg_Steps,Galar Pokedex Number,HP,Height_ft,Height_m,Hidden Ability,Index,SpAtk,SpDef,Speed,Total,Type I,Type II,Weight_kg,Weight_lbs,index
Pokemon,,,,,,,,,,,,,,,,,,,,,,,
Abomasnow,Snow Warning,,92,60.0,Frosted Tree Pokémon,White,75,5120.0,97.0,90,7.250,2.2,Soundproof,478.0,92,85,60,494.0,Ice,Grass,135.5,298.7,96.0
Abra,Synchronize,Inner Focus,20,NaN,NaN,Brown,15,NaN,NaN,25,NaN,NaN,Magic Guard,69.0,105,55,90,310.0,Psychic,,NaN,NaN,NaN
Absol,Pressure,Super Luck,130,NaN,NaN,White,60,NaN,NaN,65,NaN,NaN,Justified,388.0,75,60,75,465.0,Dark,,NaN,NaN,NaN
Accelgor,Hydration,Sticky Hold,70,75.0,Shell Out Pokémon,Red,40,3840.0,276.0,80,2.583,0.8,Unburden,617.0,100,60,145,495.0,Bug,,25.3,55.8,275.0
Aegislash,Stance Change,,50,45.0,Royal Sword Pokémon,Brown,150,5120.0,332.0,60,5.583,1.7,,681.0,50,150,60,520.0,Steel,Ghost,53.0,116.8,331.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Zoroark,Illusion,,105,NaN,NaN,Gray,60,NaN,NaN,60,NaN,NaN,,571.0,120,60,105,510.0,Dark,,NaN,NaN,NaN
Zorua,Illusion,,65,NaN,NaN,Gray,40,NaN,NaN,40,NaN,NaN,,570.0,80,40,65,330.0,Dark,,NaN,NaN,NaN
Zubat,Inner Focus,,45,NaN,NaN,Purple,35,NaN,NaN,40,NaN,NaN,Infiltrator,44.0,30,40,55,245.0,Poison,Flying,NaN,NaN,NaN
Zweilous,Hustle,,85,45.0,Hostile Pokémon,Blue,70,10240.0,387.0,72,4.583,1.4,,634.0,65,70,58,420.0,Dark,Dragon,50.0,110.2,386.0
Zygarde,Aura Break,,100,NaN,NaN,Green,121,NaN,NaN,108,NaN,NaN,,718.0,81,95,95,600.0,Dragon,Ground,NaN,NaN,NaN

### Merges and Joins
A more advanced way to join dataframes is using the `merge` or `join` operations.

For those who have worked with SQL-style databases before, you may be familiar with `merge` and `join` operations. They are done to combine two tables or dataframes which share values in certain columns. This allows us to look up entries in another dataframe using the values of our current dataframe.

In this example, we will use `merge` to get the stats for a team of pokemon. This dataframe will just contain the names and nicknames of the pokemon that we want on our team. After we perform a merge, we will get a dataframe with the respective statistics for the pokemon we've chosen.

In [29]:
# feel free to replace the names of pokemon with ones you want on your team
team_df = pd.DataFrame({'my pokemon':['Bulbasaur','Squirtle','Charmander'],
                       'nickname':['leafygurl','h2woah','toaster']})
team_df

   my pokemon   nickname
0   Bulbasaur  leafygurl
1    Squirtle     h2woah
2  Charmander    toaster

There are four merge/join types in `pandas`:
- (INNER) JOIN: Returns records that have matching values in both tables
- (LEFT) JOIN: Returns all records from the left table, and the matched records from the right table 
- (RIGHT) JOIN: Returns all records from the right table, and the matched records from the left table   
- (OUTER) JOIN: Returns all records when there is a match in either left or right table
    

 ![inner join illustration, venn diagram with intersection colored in, from w3schools sql lesson](https://www.w3schools.com/sql/img_innerjoin.gif)
  ![left join illustration, venn diagram with full left circle colored in, from w3schools sql lesson](https://www.w3schools.com/sql/img_leftjoin.gif)
  ![right join illustration, venn diagram with full right circle colored in, from w3schools sql lesson](https://www.w3schools.com/sql/img_rightjoin.gif)
  ![outer join illustration, venn diagram with union of two circles colored in, from w3schools sql lesson](https://www.w3schools.com/sql/img_fulljoin.gif)

The information that we need in order to perform a merge is:
- what dataframes to merge
- what kind of merge/join (inner/left/right/outer)
- what columns to merge on in each dataframe

Knowing this, let's look at the function signature of merge for a dataframe

In [30]:
# you can use the question mark symbol ? to examine the function signature
pokedex_df.merge?

Signature:
pokedex_df.merge(
    right: 'DataFrame | Series',
    how: 'MergeHow' = 'inner',
    on: 'IndexLabel | None' = None,
    left_on: 'IndexLabel | None' = None,
    right_on: 'IndexLabel | None' = None,
    left_index: 'bool' = False,
    right_index: 'bool' = False,
    sort: 'bool' = False,
    suffixes: 'Suffixes' = ('_x', '_y'),
    copy: 'bool | None' = None,
    indicator: 'str | bool' = False,
    validate: 'MergeValidate | None' = None,
) -> 'DataFrame'
Docstring:
Merge DataFrame or named Series objects with a database-style join.

A named Series object is treated as a DataFrame with a single named column.

The join is done on columns or indexes. If joining columns on
columns, the DataFrame indexes *will be ignored*. Otherwise if joining indexes
on indexes or indexes on a column or columns, the index will be passed on.
When performing a cross merge, no column specifications to merge on are
allowed.

.. warning::

    If both key columns contain rows where the key is a null value, those
    rows will be matched against each other. This is different from usual SQL
    join behaviour and can lead to unexpected results.

Parameters
----------
right : DataFrame or named Series
    Object to merge with.
how : {'left', 'right', 'outer', 'inner', 'cross'}, default 'inner'
    Type of merge to be performed.

    * left: use only keys from left frame, similar to a SQL left outer join;
      preserve key order.
    * right: use only keys from right frame, similar to a SQL right outer join;
      preserve key order.
    * outer: use union of keys from both frames, similar to a SQL full outer
      join; sort keys lexicographically.
    * inner: use intersection of keys from both frames, similar to a SQL inner
      join; preserve the order of the left keys.
    * cross: creates the cartesian product from both frames, preserves the order
      of the left keys.

      .. versionadded:: 1.2.0

on : label or list
    Column or index level names to join on. These must be found in both
    DataFrames. If `on` is None and not merging on indexes then this defaults
    to the intersection of the columns in both DataFrames.
left_on : label or list, or array-like
    Column or index level names to join on in the left DataFrame. Can also
    be an array or list of arrays of the length of the left DataFrame.
    These arrays are treated as if they are columns.
right_on : label or list, or array-like
    Column or index level names to join on in the right DataFrame. Can also
    be an array or list of arrays of the length of the right DataFrame.
    These arrays are treated as if they are columns.
left_index : bool, default False
    Use the index from the left DataFrame as the join key(s). If it is a
    MultiIndex, the number of keys in the other DataFrame (either the index
    or a number of columns) must match the number of levels.
right_index : bool, default False
    Use the index from the right DataFrame as the join key. Same caveats as
    left_index.
sort : bool, default False
    Sort the join keys lexicographically in the result DataFrame. If False,
    the order of the join keys depends on the join type (how keyword).
suffixes : list-like, default is ("_x", "_y")
    A length-2 sequence where each element is optionally a string
    indicating the suffix to add to overlapping column names in
    `left` and `right` respectively. Pass a value of `None` instead
    of a string to indicate that the column name from `left` or
    `right` should be left as-is, with no suffix. At least one of the
    values must not be None.
copy : bool, default True
    If False, avoid copy if possible.
indicator : bool or str, default False
    If True, adds a column to the output DataFrame called "_merge" with
    information on the source of each row. The column can be given a different
    name by providing a string argument. The column will have a Categorical
    type with the value of "left_only" for observations whose merge key only
    appears in the left DataFrame, "right_only" for observations
    whose merge key only appears in the right DataFrame, and "both"
    if the observation's merge key is found in both DataFrames.

validate : str, optional
    If specified, checks if merge is of specified type.

    * "one_to_one" or "1:1": check if merge keys are unique in both
      left and right datasets.
    * "one_to_many" or "1:m": check if merge keys are unique in left
      dataset.
    * "many_to_one" or "m:1": check if merge keys are unique in right
      dataset.
    * "many_to_many" or "m:m": allowed, but does not result in checks.

Returns
-------
DataFrame
    A DataFrame of the two merged objects.

See Also
--------
merge_ordered : Merge with optional filling/interpolation.
merge_asof : Merge on nearest keys.
DataFrame.join : Similar method using indices.

Examples
--------
>>> df1 = pd.DataFrame({'lkey': ['foo', 'bar', 'baz', 'foo'],
...                     'value': [1, 2, 3, 5]})
>>> df2 = pd.DataFrame({'rkey': ['foo', 'bar', 'baz', 'foo'],
...                     'value': [5, 6, 7, 8]})
>>> df1
    lkey value
0   foo      1
1   bar      2
2   baz      3
3   foo      5
>>> df2
    rkey value
0   foo      5
1   bar      6
2   baz      7
3   foo      8

Merge df1 and df2 on the lkey and rkey columns. The value columns have
the default suffixes, _x and _y, appended.

>>> df1.merge(df2, left_on='lkey', right_on='rkey')
  lkey  value_x rkey  value_y
0  foo        1  foo        5
1  foo        1  foo        8
2  foo        5  foo        5
3  foo        5  foo        8
4  bar        2  bar        6
5  baz        3  baz        7

Merge DataFrames df1 and df2 with specified left and right suffixes
appended to any overlapping columns.

>>> df1.merge(df2, left_on='lkey', right_on='rkey',
...           suffixes=('_left', '_right'))
  lkey  value_left rkey  value_right
0  foo           1  foo            5
1  foo           1  foo            8
2  foo           5  foo            5
3  foo           5  foo            8
4  bar           2  bar            6
5  baz           3  baz            7

Merge DataFrames df1 and df2, but raise an exception if the DataFrames have
any overlapping columns.

>>> df1.merge(df2, left_on='lkey', right_on='rkey', suffixes=(False, False))
Traceback (most recent call last):
...
ValueError: columns overlap but no suffix specified:
    Index(['value'], dtype='object')

>>> df1 = pd.DataFrame({'a': ['foo', 'bar'], 'b': [1, 2]})
>>> df2 = pd.DataFrame({'a': ['foo', 'baz'], 'c': [3, 4]})
>>> df1
      a  b
0   foo  1
1   bar  2
>>> df2
      a  c
0   foo  3
1   baz  4

>>> df1.merge(df2, how='inner', on='a')
      a  b  c
0   foo  1  3

>>> df1.merge(df2, how='left', on='a')
      a  b  c
0   foo  1  3.0
1   bar  2  NaN

>>> df1 = pd.DataFrame({'left': ['foo', 'bar']})
>>> df2 = pd.DataFrame({'right': [7, 8]})
>>> df1
    left
0   foo
1   bar
>>> df2
    right
0   7
1   8

>>> df1.merge(df2, how='cross')
   left  right
0   foo      7
1   foo      8
2   bar      7
3   bar      8
File:      /opt/conda/lib/python3.11/site-packages/pandas/core/frame.py
Type:      method

The answers to the following questions to get the team dataframe with stats are:

**what dataframes to merge?**
`team_df` and `combined_pokedex_df`
    
**what kind of merge/join (inner/left/right/outer)?**
inner or left 
    
**what columns to merge on in each dataframe**
for `team_df`, the column is `my pokemon`, for `combined_pokedex_df`, it is the index.

In [31]:
team_with_stats = team_df.merge(combined_pokedex_df, how='inner',
                               left_on='my pokemon', right_index=True)
team_with_stats

,my pokemon,nickname,Ability I,Ability II,Atk,Cap_Rate,Classification,Color,Def,Egg_Steps,Galar Pokedex Number,HP,Height_ft,Height_m,Hidden Ability,Index,SpAtk,SpDef,Speed,Total,Type I,Type II,Weight_kg,Weight_lbs,index
0,Bulbasaur,leafygurl,Overgrow,,49,NaN,NaN,Green,49,NaN,NaN,45,NaN,NaN,Chlorophyll,1.0,65,65,45,318.0,Grass,Poison,NaN,NaN,NaN
1,Squirtle,h2woah,Torrent,,48,NaN,NaN,Blue,65,NaN,NaN,44,NaN,NaN,Rain Dish,7.0,60,54,43,314.0,Water,,NaN,NaN,NaN
2,Charmander,toaster,Blaze,,52,45.0,Lizard Pokémon,Red,43,5120.0,378.0,39,2.0,0.6,Solar Power,4.0,60,50,65,309.0,Fire,,8.5,18.7,377.0

In [32]:
# we can select specific columns from the dataframe
team_with_stats.loc[:,['my pokemon','nickname','Total']]

   my pokemon   nickname  Total
0   Bulbasaur  leafygurl  318.0
1    Squirtle     h2woah  314.0
2  Charmander    toaster  309.0

### Exercise
Put together a team of pokemon by editing `team_df` and performing a `merge`. Remember that you can only have 6 pokemon on a team at once.

## Calculations and operations
There are various ways to do math to the dataframes

### Column operations
You can perform basic math element-wise between columns, such as addition, subtraction, multiplication, and division.

Note that the `gen8_pokedex_df` does not contain a `Total` stats column, so currently the gen8 pokemon have `NaN` in that column. We can fix that, because `Total` is generated as the sum of the respective `HP` `Atk` `Def` `SpAtk` `SpDef` and `Speed`. We can add the entire columns at once, without having to loop over each entry. Pandas supports vectorized operations behind the scenes.

In [33]:
# these are the entries missing 'Total' stats
combined_pokedex_df.loc[combined_pokedex_df['Total'].isnull()]

,Ability I,Ability II,Atk,Cap_Rate,Classification,Color,Def,Egg_Steps,Galar Pokedex Number,HP,Height_ft,Height_m,Hidden Ability,Index,SpAtk,SpDef,Speed,Total,Type I,Type II,Weight_kg,Weight_lbs,index
Pokemon,,,,,,,,,,,,,,,,,,,,,,,
Alcremie,Sweet Veil,NaN,60,100.0,Cream Pokémon,NaN,75,5120.0,186.0,65,1.000,0.3,Aroma Veil,NaN,110,121,64,NaN,fairy,NaN,0.5,1.1,185.0
Appletun,Ripen,Gluttony,85,45.0,Apple Nectar Pokémon,NaN,80,5120.0,207.0,110,1.333,0.4,Thick Fat,NaN,100,80,30,NaN,grass,dragon,13.0,28.7,206.0
Applin,Ripen,Gluttony,40,255.0,Apple Core Pokémon,NaN,80,5120.0,205.0,40,0.667,0.2,Bulletproof,NaN,40,40,20,NaN,grass,dragon,0.5,1.1,204.0
Arctovish,Water Absorb,Ice Body,90,45.0,Fossil Pokémon,NaN,100,8960.0,377.0,90,6.583,2.0,Slush Rush,NaN,80,90,55,NaN,water,ice,175.0,385.8,376.0
Arctozolt,Volt Absorb,Static,100,45.0,Fossil Pokémon,NaN,90,8960.0,375.0,90,7.583,2.3,Slush Rush,NaN,90,80,55,NaN,electric,ice,150.0,330.7,374.0
Arrokuda,Swift Swim,NaN,63,255.0,Rush Pokémon,NaN,40,5120.0,180.0,41,1.667,0.5,Propeller Tail,NaN,40,30,66,NaN,water,NaN,1.0,2.2,179.0
Barraskewda,Swift Swim,NaN,123,60.0,Skewer Pokémon,NaN,60,5120.0,181.0,61,4.250,1.3,Propeller Tail,NaN,60,50,136,NaN,water,NaN,30.0,66.1,180.0
Blipbug,Swarm,Compoundeyes,20,255.0,Larva Pokémon,NaN,20,3840.0,10.0,25,1.333,0.4,Telepathy,NaN,25,45,45,NaN,bug,NaN,8.0,17.6,9.0
Boltund,Strong Jaw,NaN,90,45.0,Dog Pokémon,NaN,60,5120.0,47.0,69,3.250,1.0,Competitive,NaN,90,60,121,NaN,electric,NaN,34.0,75.0,46.0
Carkol,Steam Engine,Flame Body,60,120.0,Coal Pokémon,NaN,90,3840.0,162.0,80,3.583,1.1,Flash Fire,NaN,60,70,50,NaN,rock,fire,78.0,172.0,161.0
Centiskorch,Flash Fire,White Smoke,115,75.0,Radiator Pokémon,NaN,65,5120.0,160.0,100,9.833,3.0,Flame Body,NaN,90,90,65,NaN,fire,bug,120.0,264.6,159.0
Chewtle,Strong Jaw,Shell Armor,64,255.0,Snapping Pokémon,NaN,50,5120.0,42.0,50,1.000,0.3,Swift Swim,NaN,38,38,44,NaN,water,NaN,8.5,18.7,41.0
Cinderace,Blaze,NaN,116,45.0,Striker Pokémon,NaN,75,5120.0,6.0,80,4.583,1.4,Libero,NaN,65,75,119,NaN,fire,NaN,33.0,72.8,5.0
Clobbopus,Limber,NaN,68,180.0,Tantrum Pokémon,NaN,60,6400.0,351.0,50,2.000,0.6,Technician,NaN,50,50,32,NaN,fighting,NaN,4.0,8.8,350.0
Coalossal,Steam Engine,Flame Body,80,45.0,Coal Pokémon,NaN,120,3840.0,163.0,110,9.167,2.8,Flash Fire,NaN,80,90,30,NaN,rock,fire,310.5,684.5,162.0
Copperajah,Sheer Force,NaN,130,90.0,Copperderm Pokémon,NaN,69,6400.0,303.0,122,9.833,3.0,Heavy Metal,NaN,80,69,30,NaN,steel,NaN,650.0,1433.0,302.0
Corviknight,Pressure,Unnerve,87,45.0,Raven Pokémon,NaN,105,3840.0,23.0,98,7.250,2.2,Mirror Armor,NaN,53,85,67,NaN,flying,steel,75.0,165.3,22.0
Corvisquire,Keen Eye,Unnerve,67,120.0,Raven Pokémon,NaN,55,3840.0,22.0,68,2.583,0.8,Big Pecks,NaN,43,55,77,NaN,flying,NaN,16.0,35.3,21.0
Cramorant,Gulp Missile,NaN,85,45.0,Gulp Pokémon,NaN,55,5120.0,309.0,70,2.583,0.8,NaN,NaN,85,95,85,NaN,flying,water,18.0,39.7,308.0
Cufant,Sheer Force,NaN,80,190.0,Copperderm Pokémon,NaN,49,6400.0,302.0,72,3.917,1.2,Heavy Metal,NaN,40,49,40,NaN,steel,NaN,100.0,220.5,301.0
Cursola,Weak Armor,NaN,95,30.0,Coral Pokémon,NaN,50,5120.0,237.0,60,3.250,1.0,Perish Body,NaN,145,130,30,NaN,ghost,NaN,0.4,0.9,236.0
Dottler,Swarm,Compoundeyes,35,120.0,Radome Pokémon,NaN,80,3840.0,11.0,50,1.333,0.4,Telepathy,NaN,50,90,30,NaN,bug,psychic,19.5,43.0,10.0
Dracovish,Water Absorb,Strong Jaw,90,45.0,Fossil Pokémon,NaN,100,8960.0,376.0,90,7.583,2.3,Sand Rush,NaN,70,80,75,NaN,water,dragon,215.0,474.0,375.0
Dracozolt,Volt Absorb,Hustle,100,45.0,Fossil Pokémon,NaN,90,8960.0,374.0,90,5.917,1.8,Sand Rush,NaN,80,70,75,NaN,electric,dragon,190.0,418.9,373.0
Dragapult,Clear Body,Infiltrator,120,45.0,Stealth Pokémon,NaN,75,10240.0,397.0,88,9.833,3.0,Cursed Body,NaN,100,75,142,NaN,dragon,ghost,50.0,110.2,396.0
Drakloak,Clear Body,Infiltrator,80,45.0,Caretaker Pokémon,NaN,50,10240.0,396.0,68,4.583,1.4,Cursed Body,NaN,60,50,102,NaN,dragon,ghost,11.0,24.3,395.0
Drednaw,Strong Jaw,Shell Armor,115,75.0,Bite Pokémon,NaN,90,5120.0,43.0,90,3.250,1.0,Swift Swim,NaN,48,68,74,NaN,water,rock,115.5,254.6,42.0
Dreepy,Clear Body,Infiltrator,60,45.0,Lingering Pokémon,NaN,30,10240.0,395.0,28,1.667,0.5,Cursed Body,NaN,40,30,82,NaN,dragon,ghost,2.0,4.4,394.0
Drizzile,Torrent,NaN,60,45.0,Water Lizard Pokémon,NaN,55,5120.0,8.0,65,2.333,0.7,Sniper,NaN,95,55,90,NaN,water,NaN,11.5,25.4,7.0
Dubwool,Fluffy,Steadfast,80,127.0,Sheep Pokémon,NaN,100,3840.0,35.0,72,4.250,1.3,Bulletproof,NaN,60,90,88,NaN,normal,NaN,43.0,94.8,34.0
Duraludon,Light Metal,Heavy Metal,95,45.0,Alloy Pokémon,NaN,115,7680.0,371.0,70,5.917,1.8,Stalwart,NaN,120,50,85,NaN,steel,dragon,40.0,88.2,370.0
Eiscue,Ice Face,NaN,80,60.0,Penguin Pokémon,NaN,110,6400.0,370.0,75,4.583,1.4,NaN,NaN,65,90,50,NaN,ice,NaN,89.0,196.2,369.0
Eldegoss,Cotton Down,Regenerator,50,75.0,Cotton Bloom Pokémon,NaN,90,5120.0,127.0,60,1.667,0.5,Effect Spore,NaN,80,120,60,NaN,grass,NaN,2.5,5.5,126.0
Eternatus,Pressure,NaN,85,255.0,Gigantic Pokémon,NaN,95,30720.0,400.0,140,65.583,20.0,NaN,NaN,145,95,130,NaN,poison,dragon,950.0,2094.4,399.0
Falinks,Battle Armor,NaN,100,45.0,Formation Pokémon,NaN,100,6400.0,345.0,65,9.833,3.0,Defiant,NaN,70,60,75,NaN,fighting,NaN,62.0,136.7,344.0
Farfetchd,Steadfast,NaN,95,45.0,Wild Duck Pokémon,NaN,55,5120.0,218.0,52,2.583,0.8,Scrappy,NaN,58,62,55,NaN,fighting,NaN,15.0,33.1,217.0
Flapple,Ripen,Gluttony,110,45.0,Apple Wing Pokémon,NaN,80,5120.0,206.0,70,1.000,0.3,Hustle,NaN,95,60,70,NaN,grass,dragon,1.0,2.2,205.0
Frosmoth,Shield Dust,NaN,65,75.0,Frost Moth Pokémon,NaN,60,5120.0,350.0,70,4.250,1.3,Ice Scales,NaN,125,90,65,NaN,ice,bug,42.0,92.6,349.0
Gossifleur,Cotton Down,Regenerator,40,190.0,Flowering Pokémon,NaN,60,5120.0,126.0,40,1.333,0.4,Effect Spore,NaN,40,60,10,NaN,grass,NaN,2.2,4.9,125.0
Grapploct,Limber,NaN,118,45.0,Jujitsu Pokémon,NaN,90,6400.0,352.0,80,5.250,1.6,Technician,NaN,70,80,42,NaN,fighting,NaN,39.0,86.0,351.0
Greedent,Cheek Pouch,NaN,95,90.0,Greedy Pokémon,NaN,95,5120.0,25.0,120,2.000,0.6,Gluttony,NaN,55,75,20,NaN,normal,NaN,6.0,13.2,24.0
Grimmsnarl,Prankster,Frisk,120,45.0,Bulk Up Pokémon,NaN,65,5120.0,240.0,95,4.917,1.5,Pickpocket,NaN,95,75,60,NaN,dark,fairy,61.0,134.5,239.0
Grookey,Overgrow,NaN,65,45.0,Chimp Pokémon,NaN,50,5120.0,1.0,50,1.000,0.3,Grassy Surge,NaN,40,40,65,NaN,grass,NaN,5.0,11.0,0.0
Hakamoo,Bulletproof,Soundproof,75,45.0,Scaly Pokémon,NaN,90,10240.0,393.0,55,3.917,1.2,Overcoat,NaN,65,70,65,NaN,dragon,fighting,47.0,103.6,392.0
Hatenna,Healer,Anticipation,30,235.0,Calm Pokémon,NaN,45,5120.0,241.0,42,1.333,0.4,Magic Bounce,NaN,56,53,39,NaN,psychic,NaN,3.4,7.5,240.0
Hatterene,Healer,Anticipation,90,45.0,Silent Pokémon,NaN,95,5120.0,243.0,57,6.917,2.1,Magic Bounce,NaN,136,103,29,NaN,psychic,fairy,5.1,11.2,242.0
Hattrem,Healer,Anticipation,40,120.0,Serene Pokémon,NaN,65,5120.0,242.0,57,2.000,0.6,Magic Bounce,NaN,86,73,49,NaN,psychic,NaN,4.8,10.6,241.0
Impidimp,Prankster,Frisk,45,255.0,Wily Pokémon,NaN,30,5120.0,238.0,45,1.333,0.4,Pickpocket,NaN,55,40,50,NaN,dark,fairy,5.5,12.1,237.0
Indeedee,Inner Focus,Synchronize,65,30.0,Emotion Pokémon,NaN,55,10240.0,337.0,60,2.917,0.9,Psychic Surge,NaN,105,95,95,NaN,psychic,normal,28.0,61.7,336.0
Inteleon,Torrent,NaN,85,45.0,Secret Agent Pokémon,NaN,65,5120.0,9.0,70,6.250,1.9,Sniper,NaN,125,65,120,NaN,water,NaN,45.2,99.6,8.0
Jangmoo,Bulletproof,Soundproof,55,45.0,Scaly Pokémon,NaN,65,10240.0,392.0,45,2.000,0.6,Overcoat,NaN,45,45,45,NaN,dragon,NaN,29.7,65.5,391.0
Kommoo,Bulletproof,Soundproof,110,45.0,Scaly Pokémon,NaN,125,10240.0,394.0,75,5.250,1.6,Overcoat,NaN,100,105,85,NaN,dragon,fighting,78.2,172.4,393.0
Milcery,Sweet Veil,NaN,40,200.0,Cream Pokémon,NaN,40,5120.0,185.0,45,0.667,0.2,Aroma Veil,NaN,50,61,34,NaN,fairy,NaN,0.3,0.7,184.0
MimeJr,Soundproof,Filter,25,145.0,Mime Pokémon,NaN,45,6400.0,364.0,20,2.000,0.6,Technician,NaN,70,90,60,NaN,psychic,fairy,13.0,28.7,363.0
Morgrem,Prankster,Frisk,60,120.0,Devious Pokémon,NaN,45,5120.0,239.0,65,2.583,0.8,Pickpocket,NaN,75,55,70,NaN,dark,fairy,12.5,27.6,238.0
Morpeko,Hunger Switch,NaN,95,180.0,Two-Sided Pokémon,NaN,58,2560.0,344.0,58,1.000,0.3,NaN,NaN,70,58,97,NaN,electric,dark,3.0,6.6,343.0
MrMime,Vital Spirit,Screen Cleaner,65,45.0,Barrier Pokémon,NaN,65,6400.0,365.0,50,4.250,1.3,Ice Body,NaN,90,90,100,NaN,ice,psychic,54.5,120.2,364.0
MrRime,Tangled Feet,Screen Cleaner,85,45.0,Comedian Pokémon,NaN,75,6400.0,366.0,80,4.917,1.5,Ice Body,NaN,110,100,70,NaN,ice,psychic,58.2,128.3,365.0
Nickit,Run Away,Unburden,28,255.0,Fox Pokémon,NaN,28,3840.0,29.0,40,2.000,0.6,Stakeout,NaN,47,52,50,NaN,dark,NaN,8.9,19.6,28.0
Obstagoon,Reckless,Guts,90,45.0,Blocking Pokémon,NaN,101,3840.0,33.0,93,5.250,1.6,Defiant,NaN,60,81,95,NaN,dark,normal,46.0,101.4,32.0
Orbeetle,Swarm,Frisk,45,45.0,Seven Spot Pokémon,NaN,110,3840.0,12.0,60,1.333,0.4,Telepathy,NaN,80,120,90,NaN,bug,psychic,40.8,89.9,11.0
Perrserker,Battle Armor,Tough Claws,110,90.0,Viking Pokémon,NaN,100,5120.0,183.0,70,2.583,0.8,Steely Spirit,NaN,50,60,50,NaN,steel,NaN,28.0,61.7,182.0
Pincurchin,Lightning Rod,NaN,101,75.0,Sea Urchin Pokémon,NaN,95,5120.0,353.0,48,1.000,0.3,Electric Surge,NaN,91,85,15,NaN,electric,NaN,1.0,2.2,352.0
Polteageist,Weak Armor,NaN,65,60.0,Black Tea Pokémon,NaN,65,5120.0,336.0,60,0.667,0.2,Cursed Body,NaN,134,114,70,NaN,ghost,NaN,0.4,0.9,335.0
Raboot,Blaze,NaN,86,45.0,Rabbit Pokémon,NaN,60,5120.0,5.0,65,2.000,0.6,Libero,NaN,55,60,94,NaN,fire,NaN,9.0,19.8,4.0
Rillaboom,Overgrow,NaN,125,45.0,Drummer Pokémon,NaN,90,5120.0,3.0,100,6.917,2.1,Grassy Surge,NaN,60,70,85,NaN,grass,NaN,90.0,198.4,2.0
Rolycoly,Steam Engine,Heatproof,40,255.0,Coal Pokémon,NaN,50,3840.0,161.0,30,1.000,0.3,Flash Fire,NaN,40,50,30,NaN,rock,NaN,12.0,26.5,160.0
Rookidee,Keen Eye,Unnerve,47,255.0,Tiny Bird Pokémon,NaN,35,3840.0,21.0,38,0.667,0.2,Big Pecks,NaN,33,35,57,NaN,flying,NaN,1.8,4.0,20.0
Runerigus,Wandering Spirit,NaN,95,90.0,Grudge Pokémon,NaN,145,6400.0,328.0,58,5.250,1.6,NaN,NaN,50,105,30,NaN,ground,ghost,66.6,146.8,327.0
Sandaconda,Sand Spit,Shed Skin,107,120.0,Sand Snake Pokémon,NaN,125,5120.0,313.0,72,12.500,3.8,Sand Veil,NaN,65,70,71,NaN,ground,NaN,65.5,144.4,312.0
Scorbunny,Blaze,NaN,71,45.0,Rabbit Pokémon,NaN,40,5120.0,4.0,50,1.000,0.3,Libero,NaN,40,40,69,NaN,fire,NaN,4.5,9.9,3.0
Silicobra,Sand Spit,Shed Skin,57,255.0,Sand Snake Pokémon,NaN,75,5120.0,312.0,52,7.250,2.2,Sand Veil,NaN,35,50,46,NaN,ground,NaN,7.6,16.8,311.0
Sinistea,Weak Armor,NaN,45,120.0,Black Tea Pokémon,NaN,45,5120.0,335.0,40,0.333,0.1,Cursed Body,NaN,74,54,50,NaN,ghost,NaN,0.2,0.4,334.0
Sirfetchd,Steadfast,NaN,135,45.0,Wild Duck Pokémon,NaN,95,5120.0,219.0,62,2.583,0.8,Scrappy,NaN,68,82,65,NaN,fighting,NaN,117.0,257.9,218.0
Sizzlipede,Flash Fire,White Smoke,65,190.0,Radiator Pokémon,NaN,45,5120.0,159.0,50,2.333,0.7,Flame Body,NaN,50,50,45,NaN,fire,bug,1.0,2.2,158.0
Skwovet,Cheek Pouch,NaN,55,255.0,Cheeky Pokémon,NaN,55,5120.0,24.0,70,1.000,0.3,Gluttony,NaN,35,35,25,NaN,normal,NaN,2.5,5.5,23.0
Snom,Shield Dust,NaN,25,190.0,Worm Pokémon,NaN,35,5120.0,349.0,30,1.000,0.3,Ice Scales,NaN,45,30,20,NaN,ice,bug,3.8,8.4,348.0
Sobble,Torrent,NaN,40,45.0,Water Lizard Pokémon,NaN,40,5120.0,7.0,50,1.000,0.3,Sniper,NaN,70,40,70,NaN,water,NaN,4.0,8.8,6.0
Stonjourner,Power Spot,NaN,125,60.0,Big Rock Pokémon,NaN,135,6400.0,369.0,100,8.167,2.5,NaN,NaN,20,20,70,NaN,rock,NaN,520.0,1146.4,368.0
Thievul,Run Away,Unburden,58,127.0,Fox Pokémon,NaN,58,3840.0,30.0,70,3.917,1.2,Stakeout,NaN,87,92,90,NaN,dark,NaN,19.9,43.9,29.0
Thwackey,Overgrow,NaN,85,45.0,Beat Pokémon,NaN,70,5120.0,2.0,70,2.333,0.7,Grassy Surge,NaN,55,60,80,NaN,grass,NaN,14.0,30.9,1.0
Toxel,Rattled,Static,38,75.0,Baby Pokémon,NaN,35,6400.0,310.0,40,1.333,0.4,Klutz,NaN,54,35,40,NaN,electric,poison,11.0,24.3,309.0
Toxtricity,Punk Rock,Plus,98,45.0,Punk Pokémon,NaN,70,6400.0,311.0,75,5.250,1.6,Technician,NaN,114,70,75,NaN,electric,poison,40.0,88.2,310.0
TypeNull,Battle Armor,NaN,95,3.0,Synthetic Pokémon,NaN,95,30720.0,381.0,95,6.250,1.9,NaN,NaN,95,95,59,NaN,normal,NaN,120.5,265.7,380.0
Wishiwashi,Schooling,NaN,20,60.0,Small Fry Pokémon,NaN,20,3840.0,155.0,45,0.667,0.2,NaN,NaN,25,25,40,NaN,water,NaN,0.3,0.7,154.0
Wooloo,Fluffy,Run Away,40,255.0,Sheep Pokémon,NaN,55,3840.0,34.0,42,2.000,0.6,Bulletproof,NaN,40,45,48,NaN,normal,NaN,6.0,13.2,33.0
Yamper,Ball Fetch,NaN,45,255.0,Puppy Pokémon,NaN,50,5120.0,46.0,59,1.000,0.3,Rattled,NaN,40,50,26,NaN,electric,NaN,13.5,29.8,45.0
Zacian,Intrepid Sword,NaN,130,10.0,Warrior Pokémon,NaN,115,30720.0,398.0,92,9.167,2.8,NaN,NaN,80,115,138,NaN,fairy,NaN,110.0,242.5,397.0
Zamazenta,Dauntless Shield,NaN,130,10.0,Warrior Pokémon,NaN,115,30720.0,399.0,92,9.500,2.9,NaN,NaN,80,115,138,NaN,fighting,NaN,210.0,463.0,398.0

In [34]:
combined_pokedex_df['Total'] = combined_pokedex_df['HP']\
                               + combined_pokedex_df['Atk']\
                               + combined_pokedex_df['Def']\
                               + combined_pokedex_df['SpAtk']\
                               + combined_pokedex_df['SpDef']\
                               + combined_pokedex_df['Speed']

In [35]:
pokedex_df['Total']/ pokedex_df['HP'] # computes the ratio between total stats and HP

Index
1.0      7.066667
2.0      6.750000
3.0      6.562500
4.0      7.923077
5.0      6.982759
           ...
798.0    9.661017
799.0    2.556054
800.0    6.185567
801.0    7.500000
802.0    6.666667
Length: 820, dtype: float64

### Universal functions
Universal functions can operate on entire dataframes or slices of dataframes. They return a dataframe copy with the same index as the original dataframe. Numpy universal functions can be applied to any numeric dataframe or slice.

In [36]:
np.log(pokedex_df.loc[:,'HP':'Total'].astype(float)) # take natural log of all stats
# again, these functions operate on each element independently, and return a dataframe with the same index and size of input

             HP       Atk       Def     SpAtk     SpDef     Speed     Total
Index
1.0    3.806662  3.891820  3.891820  4.174387  4.174387  3.806662  5.762051
2.0    4.094345  4.127134  4.143135  4.382027  4.382027  4.094345  6.003887
3.0    4.382027  4.406719  4.418841  4.605170  4.605170  4.382027  6.263398
4.0    3.663562  3.951244  3.761200  4.094345  3.912023  4.174387  5.733341
5.0    4.060443  4.158883  4.060443  4.382027  4.174387  4.382027  6.003887
...         ...       ...       ...       ...       ...       ...       ...
798.0  4.077537  5.198497  4.875197  4.077537  3.433987  4.691348  6.345636
799.0  5.407172  4.615121  3.970292  4.574711  3.970292  3.761200  6.345636
800.0  4.574711  4.672829  4.615121  4.844187  4.488636  4.369448  6.396930
801.0  4.382027  4.553877  4.744932  4.867534  4.744932  4.174387  6.396930
802.0  4.499810  4.828314  4.382027  4.499810  4.499810  4.828314  6.396930

[820 rows x 7 columns]

### .apply()
You can apply an arbitrary function to each row or column using the `.apply()` function.

If you pass the name of a function (e.g. np.mean, or the name of any function you've written), you can apply it to either each column, or each row using `.apply()`

In [37]:
pokedex_df.loc[:,'Atk':'Speed'].apply(np.mean) # applies the function np.mean() to each column

Atk      76.115854
Def      71.919512
SpAtk    69.957317
SpDef    70.370732
Speed    66.140244
dtype: float64

In [38]:
pokedex_df.loc[:,'Atk':'Speed'].apply(np.mean, axis=1) # if you wanted to apply it to each row instead, use the argument axis=1

Index
1.0       54.6
2.0       69.0
3.0       89.0
4.0       54.0
5.0       69.4
         ...
798.0    102.2
799.0     69.4
800.0    100.6
801.0    104.0
802.0    102.0
Length: 820, dtype: float64

The above example is actually a bit unnecessary. There are several built-in functions in dataframes, including a `.mean()` which has the same functionality.

In [39]:
pokedex_df.loc[:,'Atk':'Speed'].mean()

Atk      76.115854
Def      71.919512
SpAtk    69.957317
SpDef    70.370732
Speed    66.140244
dtype: float64

In [40]:
pokedex_df.loc[:,'Atk':'Speed'].mean(axis=1) #applies per row

Index
1.0       54.6
2.0       69.0
3.0       89.0
4.0       54.0
5.0       69.4
         ...
798.0    102.2
799.0     69.4
800.0    100.6
801.0    104.0
802.0    102.0
Length: 820, dtype: float64

Most [descriptive statistics](https://pandas.pydata.org/pandas-docs/stable/reference/frame.html#computations-descriptive-stats) (median, mode, standard deviation, count, quantile, etc) have built-in functions. Where `.apply()` really shines, however, is for applying custom functions. 

To show that functionality, let's take a sidebar and talk about lambda functions.

#### Lambda functions
Sometimes you want to define a function, but you don't want to write the whole function declaration setup 
```
def functionname(inputs):
  ...
  return outputs
```

In those situations, you can write lambda (also known as anonymous) functions. The syntax for a lambda function is:

```
functionname = lambda x: operations_on_x
```

For example, if you wanted to write a function that squares the input, you could write:

In [41]:
square_it = lambda x: x**2 # recall that ** is exponentiation in python, this function returns the square of the input
for num in range(10):
  print(square_it(num))

0
1
4
9
16
25
36
49
64
81

This is especially useful if some function takes another function as an argument, like panda's `.apply()`

The typical usage of `.apply()` is:

`dataframe_obj.apply(functionname)`, which calls `functionname` on each column of `dataframe_obj`

However, you can replace `functionname` with a lambda function. In this example, we use the following lambda function:

```lambda col: [np.min(col), np.max(col)]```

The word `col` represents the argument, and then to the right of the colon, we return a list with two elements: the minimum and maximum values of the column

In [42]:
stats_ranges = pokedex_df.loc[:,'HP':'Total'].apply(lambda col: [np.min(col), np.max(col)])
print(stats_ranges)

    HP  Atk  Def  SpAtk  SpDef  Speed  Total
0    1    5    5     10     20      5    175
1  255  181  230    180    230    180    720

the above can be expanded into a dataframe:

In [43]:
pokedex_df.loc[:,'HP':'Total'].apply(lambda col: [np.min(col), np.mean(col), np.max(col)], result_type='expand')
# each respective row corresponds to the function applied to the column

,HP,Atk,Def,SpAtk,SpDef,Speed,Total
0,1.00000,5.000000,5.000000,10.000000,20.000000,5.000000,175.000000
1,68.60122,76.115854,71.919512,69.957317,70.370732,66.140244,423.104878
2,255.00000,181.000000,230.000000,180.000000,230.000000,180.000000,720.000000

In [44]:
# we can rename the rows to make it more interpretable. Also note the backslash \
# character allows a command to continue onto the next line, ignoring whitespace
pokedex_df.loc[:,'HP':'Total']\
          .apply(lambda col: [np.min(col), np.mean(col), np.max(col)], result_type='expand')\
          .rename({0:'min', 1:'mean', 2:'max'})

,HP,Atk,Def,SpAtk,SpDef,Speed,Total
min,1.00000,5.000000,5.000000,10.000000,20.000000,5.000000,175.000000
mean,68.60122,76.115854,71.919512,69.957317,70.370732,66.140244,423.104878
max,255.00000,181.000000,230.000000,180.000000,230.000000,180.000000,720.000000

### Groupby
Dataframes can be grouped by column values, and operations can be applied to each group

In [45]:
# counts the number of pokemon of each type combination
pokedex_df.groupby(['Type I','Type II'])['Total'].count()

Type I  Type II
Bug                 18
        Electric     4
        Fairy        2
        Fighting     3
        Fire         2
                    ..
Water   Ice          3
        Poison       3
        Psychic      5
        Rock         4
        Steel        1
Name: Total, Length: 163, dtype: int64

In [46]:
# gets the range of stats for each type combination
pokedex_df.groupby(['Type I','Type II'])['Total'].apply(lambda col: [np.min(col), np.max(col)])

Type I  Type II
Bug                 [194, 500]
        Electric    [319, 500]
        Fairy       [304, 464]
        Fighting    [500, 570]
        Fire        [360, 550]
                       ...
Water   Ice         [475, 535]
        Poison      [335, 515]
        Psychic     [315, 520]
        Rock        [355, 495]
        Steel       [530, 530]
Name: Total, Length: 163, dtype: object

# Multi-level indexing
In this section, we'll cover some more advanced topics in pandas, including 
*   Multi-indexing
*   Pivot tables

We'll be introducing some more data to play with, based on state populations over time

In [47]:
state_populations_url = 'https://raw.githubusercontent.com/jakevdp/data-USstates/master/state-population.csv'
state_abbrevs_url = 'https://raw.githubusercontent.com/jakevdp/data-USstates/master/state-abbrevs.csv'
state_areas_url = 'https://raw.githubusercontent.com/jakevdp/data-USstates/master/state-areas.csv'

state_areas = pd.read_csv(state_areas_url, index_col='state')
state_areas.head() # just print top 5 rows

            area (sq. mi)
state
Alabama             52423
Alaska             656425
Arizona            114006
Arkansas            53182
California         163707

In [48]:
state_abbrevs = pd.read_csv(state_abbrevs_url)
state_abbrevs.head()

        state abbreviation
0     Alabama           AL
1      Alaska           AK
2     Arizona           AZ
3    Arkansas           AR
4  California           CA

In [49]:
state_populations = pd.read_csv(state_populations_url) 
state_populations.head(10) #print first 10 rows

  state/region     ages  year  population
0           AL  under18  2012   1117489.0
1           AL    total  2012   4817528.0
2           AL  under18  2010   1130966.0
3           AL    total  2010   4785570.0
4           AL  under18  2011   1125763.0
5           AL    total  2011   4801627.0
6           AL    total  2009   4757938.0
7           AL  under18  2009   1134192.0
8           AL  under18  2013   1111481.0
9           AL    total  2013   4833722.0

In [50]:
state_populations.tail()

     state/region     ages  year   population
2539          USA    total  2010  309326295.0
2540          USA  under18  2011   73902222.0
2541          USA    total  2011  311582564.0
2542          USA  under18  2012   73708179.0
2543          USA    total  2012  313873685.0

Note that the state populations are just listed by abbreviations. It may be useful to include the state names as a column in a table. We have this information in the `state_abbrevs` table. We'd like to merge it with the population data.

The function `pd.merge()` merges two dataframes using set logic.

In [99]:
merged = pd.merge(state_populations, state_abbrevs, how='outer',
                 left_on='state/region', right_on='abbreviation')
# The arguments left_on and right_on specify what columns to join on. It looks for matching values in each dataframe
# and fills in the additional columns of the merged dataframe based on the matching data
# The 'how' argument specifies what kind of join. Outer means keep all entries even if one does not show up in the other
# conversely, 'inner' discards rows where a corresponding entry does not exist in the other
merged

     state/region     ages  year   population                 state  \
0              AL  under18  2012    1117489.0               Alabama
1              AL    total  2012    4817528.0               Alabama
2              AL  under18  2010    1130966.0               Alabama
3              AL    total  2010    4785570.0               Alabama
4              AL  under18  2011    1125763.0               Alabama
5              AL    total  2011    4801627.0               Alabama
6              AL    total  2009    4757938.0               Alabama
7              AL  under18  2009    1134192.0               Alabama
8              AL  under18  2013    1111481.0               Alabama
9              AL    total  2013    4833722.0               Alabama
10             AL    total  2007    4672840.0               Alabama
11             AL  under18  2007    1132296.0               Alabama
12             AL    total  2008    4718206.0               Alabama
13             AL  under18  2008    1134927.0               Alabama
14             AL    total  2005    4569805.0               Alabama
15             AL  under18  2005    1117229.0               Alabama
16             AL    total  2006    4628981.0               Alabama
17             AL  under18  2006    1126798.0               Alabama
18             AL    total  2004    4530729.0               Alabama
19             AL  under18  2004    1113662.0               Alabama
20             AL    total  2003    4503491.0               Alabama
21             AL  under18  2003    1113083.0               Alabama
22             AL    total  2001    4467634.0               Alabama
23             AL  under18  2001    1120409.0               Alabama
24             AL    total  2002    4480089.0               Alabama
25             AL  under18  2002    1116590.0               Alabama
26             AL  under18  1999    1121287.0               Alabama
27             AL    total  1999    4430141.0               Alabama
28             AL    total  2000    4452173.0               Alabama
29             AL  under18  2000    1122273.0               Alabama
30             AL    total  1998    4404701.0               Alabama
31             AL  under18  1998    1118252.0               Alabama
32             AL  under18  1997    1122893.0               Alabama
33             AL    total  1997    4367935.0               Alabama
34             AL    total  1996    4331103.0               Alabama
35             AL    total  1995    4296800.0               Alabama
36             AL  under18  1995    1110553.0               Alabama
37             AL  under18  1996    1112092.0               Alabama
38             AL    total  1994    4260229.0               Alabama
39             AL    total  1993    4214202.0               Alabama
40             AL  under18  1993    1085606.0               Alabama
41             AL  under18  1994    1097180.0               Alabama
42             AL  under18  1992    1072873.0               Alabama
43             AL    total  1992    4154014.0               Alabama
44             AL    total  1991    4099156.0               Alabama
45             AL  under18  1991    1060794.0               Alabama
46             AL  under18  1990    1050041.0               Alabama
47             AL    total  1990    4050055.0               Alabama
48             AK    total  1990     553290.0                Alaska
49             AK  under18  1990     177502.0                Alaska
50             AK    total  1992     588736.0                Alaska
51             AK  under18  1991     182180.0                Alaska
52             AK  under18  1992     184878.0                Alaska
53             AK    total  1994     603308.0                Alaska
54             AK  under18  1994     187439.0                Alaska
55             AK    total  1991     570193.0                Alaska
56             AK    total  1993     599434.0                Alaska
57             AK  under18  1993     187190.0                Alaska
58             AK    total  1995     604412.0                Alaska
59             AK  under18  1995     184990.0                Alaska
60             AK    total  1996     608569.0                Alaska
61             AK  under18  1996     185360.0                Alaska
62             AK  under18  1997     188280.0                Alaska
63             AK  under18  1998     192636.0                Alaska
64             AK    total  1998     619933.0                Alaska
65             AK    total  1997     612968.0                Alaska
66             AK  under18  1999     191422.0                Alaska
67             AK    total  1999     624779.0                Alaska
68             AK    total  2000     627963.0                Alaska
69             AK  under18  2000     190615.0                Alaska
70             AK    total  2001     633714.0                Alaska
71             AK  under18  2001     188771.0                Alaska
72             AK    total  2002     642337.0                Alaska
73             AK  under18  2002     188482.0                Alaska
74             AK    total  2003     648414.0                Alaska
75             AK  under18  2003     186843.0                Alaska
76             AK    total  2004     659286.0                Alaska
77             AK  under18  2004     186335.0                Alaska
78             AK    total  2005     666946.0                Alaska
79             AK  under18  2005     185304.0                Alaska
80             AK    total  2006     675302.0                Alaska
81             AK  under18  2006     185580.0                Alaska
82             AK    total  2007     680300.0                Alaska
83             AK  under18  2007     184344.0                Alaska
84             AK    total  2008     687455.0                Alaska
85             AK  under18  2008     183124.0                Alaska
86             AK  under18  2013     188132.0                Alaska
87             AK    total  2013     735132.0                Alaska
88             AK    total  2009     698895.0                Alaska
89             AK  under18  2009     186351.0                Alaska
90             AK  under18  2010     187902.0                Alaska
91             AK    total  2010     713868.0                Alaska
92             AK  under18  2011     188329.0                Alaska
93             AK    total  2011     723375.0                Alaska
94             AK  under18  2012     188162.0                Alaska
95             AK    total  2012     730307.0                Alaska
96             AZ  under18  2012    1617149.0               Arizona
97             AZ    total  2012    6551149.0               Arizona
98             AZ  under18  2011    1616353.0               Arizona
99             AZ    total  2011    6468796.0               Arizona
100            AZ  under18  2010    1628563.0               Arizona
101            AZ    total  2010    6408790.0               Arizona
102            AZ  under18  2013    1616814.0               Arizona
103            AZ    total  2013    6626624.0               Arizona
104            AZ    total  2009    6343154.0               Arizona
105            AZ  under18  2009    1627343.0               Arizona
106            AZ    total  2007    6167681.0               Arizona
107            AZ  under18  2007    1607895.0               Arizona
108            AZ    total  2008    6280362.0               Arizona
109            AZ  under18  2008    1628651.0               Arizona
110            AZ    total  2005    5839077.0               Arizona
111            AZ  under18  2005    1529168.0               Arizona
112            AZ    total  2006    6029141.0               Arizona
113            AZ  under18  2006    1574867.0               Arizona
114            AZ    total  2004    5652404.0               Arizona
115            AZ  under18  2004    1484454.0               Arizona
116            AZ    total  2003    5510364.0               Arizona
117            AZ  under18  2003    1453671.0               Arizona
118            AZ    total  2001    5273477.0               Arizona
119            AZ  under18  2001    1399015.0               Arizona
120            AZ    total  2002    5396255.0               Arizona
121            AZ  under18  2002    1427938.0               Arizona
122            AZ  under18  1999    1332396.0               Arizona
123            AZ    total  1999    5023823.0               Arizona
124            AZ    total  2000    5160586.0               Arizona
125            AZ  under18  2000    1373414.0               Arizona
126            AZ    total  1998    4883342.0               Arizona
127            AZ  under18  1998    1285794.0               Arizona
128            AZ    total  1997    4736990.0               Arizona
129            AZ  under18  1997    1237159.0               Arizona
130            AZ  under18  1996    1215285.0               Arizona
131            AZ    total  1996    4586940.0               Arizona
132            AZ    total  1995    4432499.0               Arizona
133            AZ  under18  1995    1173391.0               Arizona
134            AZ    total  1993    4065440.0               Arizona
135            AZ  under18  1993    1094233.0               Arizona
136            AZ  under18  1994    1119857.0               Arizona
137            AZ    total  1994    4245089.0               Arizona
138            AZ  under18  1992    1055572.0               Arizona
139            AZ  under18  1991    1028285.0               Arizona
140            AZ    total  1991    3788576.0               Arizona
141            AZ    total  1992    3915740.0               Arizona
142            AZ  under18  1990    1006040.0               Arizona
143            AZ    total  1990    3684097.0               Arizona
144            AR  under18  1990     620933.0              Arkansas
145            AR    total  1990    2356586.0              Arkansas
146            AR    total  1991    2383144.0              Arkansas
147            AR  under18  1991     626212.0              Arkansas
148            AR  under18  1992     638269.0              Arkansas
149            AR    total  1992    2415984.0              Arkansas
150            AR  under18  1994     653842.0              Arkansas
151            AR    total  1994    2494019.0              Arkansas
152            AR    total  1993    2456303.0              Arkansas
153            AR  under18  1993     643474.0              Arkansas
154            AR  under18  1995     667671.0              Arkansas
155            AR    total  1995    2535399.0              Arkansas
156            AR  under18  1996     677912.0              Arkansas
157            AR    total  1996    2572109.0              Arkansas
158            AR  under18  1998     683637.0              Arkansas
159            AR    total  1997    2601091.0              Arkansas
160            AR  under18  1997     680203.0              Arkansas
161            AR    total  1998    2626289.0              Arkansas
162            AR    total  2000    2678588.0              Arkansas
163            AR  under18  2000     680378.0              Arkansas
164            AR  under18  1999     681940.0              Arkansas
165            AR    total  1999    2651860.0              Arkansas
166            AR    total  2002    2705927.0              Arkansas
167            AR  under18  2002     678798.0              Arkansas
168            AR    total  2001    2691571.0              Arkansas
169            AR  under18  2001     679606.0              Arkansas
170            AR    total  2004    2749686.0              Arkansas
171            AR  under18  2004     683166.0              Arkansas
172            AR    total  2003    2724816.0              Arkansas
173            AR  under18  2003     679579.0              Arkansas
174            AR    total  2006    2821761.0              Arkansas
175            AR  under18  2006     697842.0              Arkansas
176            AR    total  2005    2781097.0              Arkansas
177            AR  under18  2005     689787.0              Arkansas
178            AR    total  2008    2874554.0              Arkansas
179            AR  under18  2008     705725.0              Arkansas
180            AR    total  2007    2848650.0              Arkansas
181            AR  under18  2007     702737.0              Arkansas
182            AR    total  2009    2896843.0              Arkansas
183            AR  under18  2009     707886.0              Arkansas
184            AR  under18  2013     709866.0              Arkansas
185            AR    total  2013    2959373.0              Arkansas
186            AR  under18  2011     710576.0              Arkansas
187            AR    total  2011    2938506.0              Arkansas
188            AR  under18  2010     711947.0              Arkansas
189            AR    total  2010    2922280.0              Arkansas
190            AR  under18  2012     710471.0              Arkansas
191            AR    total  2012    2949828.0              Arkansas
192            CA  under18  2012    9209007.0            California
193            CA    total  2012   37999878.0            California
194            CA  under18  2011    9252336.0            California
195            CA    total  2011   37668681.0            California
196            CA  under18  2010    9284094.0            California
197            CA    total  2010   37333601.0            California
198            CA  under18  2013    9174877.0            California
199            CA    total  2013   38332521.0            California
200            CA    total  2009   36961229.0            California
201            CA  under18  2009    9294501.0            California
202            CA    total  2007   36250311.0            California
203            CA  under18  2007    9335620.0            California
204            CA    total  2008   36604337.0            California
205            CA  under18  2008    9321621.0            California
206            CA    total  2005   35827943.0            California
207            CA  under18  2005    9405565.0            California
208            CA    total  2006   36021202.0            California
209            CA  under18  2006    9370884.0            California
210            CA    total  2003   35253159.0            California
211            CA  under18  2003    9404594.0            California
212            CA    total  2004   35574576.0            California
213            CA  under18  2004    9418497.0            California
214            CA    total  2001   34479458.0            California
215            CA  under18  2001    9325466.0            California
216            CA    total  2002   34871843.0            California
217            CA  under18  2002    9365142.0            California
218            CA  under18  1999    9207878.0            California
219            CA    total  1999   33499204.0            California
220            CA    total  2000   33987977.0            California
221            CA  under18  2000    9267089.0            California
222            CA  under18  1998    9163238.0            California
223            CA    total  1998   32987675.0            California
224            CA  under18  1997    9135359.0            California
225            CA    total  1997   32486010.0            California
226            CA  under18  1996    9079519.0            California
227            CA    total  1996   32018834.0            California
228            CA    total  1995   31696582.0            California
229            CA  under18  1995    8920578.0            California
230            CA    total  1993   31274928.0            California
231            CA  under18  1993    8624810.0            California
232            CA  under18  1994    8790058.0            California
233            CA    total  1994   31484435.0            California
234            CA    total  1991   30470736.0            California
235            CA  under18  1991    8245605.0            California
236            CA  under18  1992    8439647.0            California
237            CA    total  1992   30974659.0            California
238            CA  under18  1990    7980501.0            California
239            CA    total  1990   29959515.0            California
240            CO    total  1990    3307618.0              Colorado
241            CO  under18  1990     881640.0              Colorado
242            CO    total  1992    3495939.0              Colorado
243            CO  under18  1992     925577.0              Colorado
244            CO  under18  1991     896537.0              Colorado
245            CO    total  1991    3387119.0              Colorado
246            CO    total  1994    3724168.0              Colorado
247            CO  under18  1994     966412.0              Colorado
248            CO  under18  1993     947806.0              Colorado
249            CO    total  1993    3613734.0              Colorado
250            CO  under18  1995     984310.0              Colorado
251            CO    total  1995    3826653.0              Colorado
252            CO    total  1996    3919972.0              Colorado
253            CO  under18  1996    1003946.0              Colorado
254            CO  under18  1997    1030557.0              Colorado
255            CO    total  1997    4018293.0              Colorado
256            CO    total  1998    4116639.0              Colorado
257            CO  under18  1998    1060066.0              Colorado
258            CO    total  2000    4326921.0              Colorado
259            CO  under18  2000    1106676.0              Colorado
260            CO    total  1999    4226018.0              Colorado
261            CO  under18  1999    1083938.0              Colorado
262            CO    total  2002    4490406.0              Colorado
263            CO  under18  2002    1138273.0              Colorado
264            CO    total  2001    4425687.0              Colorado
265            CO  under18  2001    1126647.0              Colorado
266            CO    total  2004    4575013.0              Colorado
267            CO  under18  2004    1146369.0              Colorado
268            CO    total  2003    4528732.0              Colorado
269            CO  under18  2003    1144597.0              Colorado
270            CO    total  2006    4720423.0              Colorado
271            CO  under18  2006    1171832.0              Colorado
272            CO    total  2005    4631888.0              Colorado
273            CO  under18  2005    1156399.0              Colorado
274            CO    total  2008    4889730.0              Colorado
275            CO  under18  2008    1203289.0              Colorado
276            CO    total  2007    4803868.0              Colorado
277            CO  under18  2007    1189434.0              Colorado
278            CO    total  2009    4972195.0              Colorado
279            CO  under18  2009    1217213.0              Colorado
280            CO  under18  2013    1237932.0              Colorado
281            CO    total  2013    5268367.0              Colorado
282            CO  under18  2010    1226619.0              Colorado
283            CO    total  2010    5048196.0              Colorado
284            CO  under18  2011    1230178.0              Colorado
285            CO    total  2011    5118400.0              Colorado
286            CO  under18  2012    1232864.0              Colorado
287            CO    total  2012    5189458.0              Colorado
288            CT  under18  2012     794959.0           Connecticut
289            CT    total  2012    3591765.0           Connecticut
290            CT  under18  2011     805109.0           Connecticut
291            CT    total  2011    3588948.0           Connecticut
292            CT  under18  2010     814187.0           Connecticut

In [100]:
# we can also drop the unnecessary extra abbreviation column now
merged = merged.drop('abbreviation', axis=1) #drop from columns
merged.head()

  state/region     ages  year  population    state
0           AL  under18  2012   1117489.0  Alabama
1           AL    total  2012   4817528.0  Alabama
2           AL  under18  2010   1130966.0  Alabama
3           AL    total  2010   4785570.0  Alabama
4           AL  under18  2011   1125763.0  Alabama

In [101]:
# we can check if there were any missing values
merged.isnull().any()

state/region    False
ages            False
year            False
population       True
state            True
dtype: bool

In [102]:
# let's see where the issue is. What entries are missing population entries?
merged.loc[merged['population'].isnull()]

     state/region     ages  year  population state
2448           PR  under18  1990         NaN   NaN
2449           PR    total  1990         NaN   NaN
2450           PR    total  1991         NaN   NaN
2451           PR  under18  1991         NaN   NaN
2452           PR    total  1993         NaN   NaN
2453           PR  under18  1993         NaN   NaN
2454           PR  under18  1992         NaN   NaN
2455           PR    total  1992         NaN   NaN
2456           PR  under18  1994         NaN   NaN
2457           PR    total  1994         NaN   NaN
2458           PR    total  1995         NaN   NaN
2459           PR  under18  1995         NaN   NaN
2460           PR  under18  1996         NaN   NaN
2461           PR    total  1996         NaN   NaN
2462           PR  under18  1998         NaN   NaN
2463           PR    total  1998         NaN   NaN
2464           PR    total  1997         NaN   NaN
2465           PR  under18  1997         NaN   NaN
2466           PR    total  1999         NaN   NaN
2467           PR  under18  1999         NaN   NaN

In [103]:
# what about where there's no state entry?
merged.loc[merged['state'].isnull(), 'state/region']

2448     PR
2449     PR
2450     PR
2451     PR
2452     PR
2453     PR
2454     PR
2455     PR
2456     PR
2457     PR
2458     PR
2459     PR
2460     PR
2461     PR
2462     PR
2463     PR
2464     PR
2465     PR
2466     PR
2467     PR
2468     PR
2469     PR
2470     PR
2471     PR
2472     PR
2473     PR
2474     PR
2475     PR
2476     PR
2477     PR
2478     PR
2479     PR
2480     PR
2481     PR
2482     PR
2483     PR
2484     PR
2485     PR
2486     PR
2487     PR
2488     PR
2489     PR
2490     PR
2491     PR
2492     PR
2493     PR
2494     PR
2495     PR
2496    USA
2497    USA
2498    USA
2499    USA
2500    USA
2501    USA
2502    USA
2503    USA
2504    USA
2505    USA
2506    USA
2507    USA
2508    USA
2509    USA
2510    USA
2511    USA
2512    USA
2513    USA
2514    USA
2515    USA
2516    USA
2517    USA
2518    USA
2519    USA
2520    USA
2521    USA
2522    USA
2523    USA
2524    USA
2525    USA
2526    USA
2527    USA
2528    USA
2529    USA
2530    USA
2531    USA
2532    USA
2533    USA
2534    USA
2535    USA
2536    USA
2537    USA
2538    USA
2539    USA
2540    USA
2541    USA
2542    USA
2543    USA
Name: state/region, dtype: object

In [104]:
# more concicely, we can use .unique() to only see the unique values
merged.loc[merged['state'].isnull(), 'state/region'].unique()

array(['PR', 'USA'], dtype=object)

In [105]:
# We can fix this easily
merged.loc[merged['state/region'] == 'PR', 'state'] = 'Puerto Rico'
merged.loc[merged['state/region'] == 'USA', 'state'] = 'United States'
merged.isnull().any()

state/region    False
ages            False
year            False
population       True
state           False
dtype: bool

In [106]:
# now let's combine the data with the area data
final = pd.merge(merged, state_areas, on='state', how='left')
final.head()

  state/region     ages  year  population    state  area (sq. mi)
0           AL  under18  2012   1117489.0  Alabama        52423.0
1           AL    total  2012   4817528.0  Alabama        52423.0
2           AL  under18  2010   1130966.0  Alabama        52423.0
3           AL    total  2010   4785570.0  Alabama        52423.0
4           AL  under18  2011   1125763.0  Alabama        52423.0

In [107]:
# we can use the .query() syntax to search for specific data
data2010 = final.query("year == 2010 & ages == 'total'") # specify column name 
data2010.set_index('state', inplace=True) # equivalent to data2010 = data2010.set_index('state')
data2010.head()

           state/region   ages  year  population  area (sq. mi)
state
Alabama              AL  total  2010   4785570.0        52423.0
Alaska               AK  total  2010    713868.0       656425.0
Arizona              AZ  total  2010   6408790.0       114006.0
Arkansas             AR  total  2010   2922280.0        53182.0
California           CA  total  2010  37333601.0       163707.0

In [108]:
# Let's compute the density of each state and then sort by density
density = data2010['population'] / data2010['area (sq. mi)']
density.sort_values(ascending=False, inplace=True)
density

state
District of Columbia    8898.897059
Puerto Rico             1058.665149
New Jersey              1009.253268
Rhode Island             681.339159
Connecticut              645.600649
Massachusetts            621.815538
Maryland                 466.445797
Delaware                 460.445752
New York                 356.094135
Florida                  286.597129
Pennsylvania             275.966651
Ohio                     257.549634
California               228.051342
Illinois                 221.687472
Virginia                 187.622273
Indiana                  178.197831
North Carolina           177.617157
Georgia                  163.409902
Tennessee                150.825298
South Carolina           144.854594
New Hampshire            140.799273
Hawaii                   124.746707
Kentucky                 107.586994
Michigan                 102.015794
Washington                94.557817
Texas                     93.987655
Alabama                   91.287603
Louisiana                 87.676099
Wisconsin                 86.851900
Missouri                  86.015622
West Virginia             76.519582
Vermont                   65.085075
Mississippi               61.321530
Minnesota                 61.078373
Arizona                   56.214497
Arkansas                  54.948667
Iowa                      54.202751
Oklahoma                  53.778278
Colorado                  48.493718
Oregon                    39.001565
Maine                     37.509990
Kansas                    34.745266
Utah                      32.677188
Nevada                    24.448796
Nebraska                  23.654153
Idaho                     18.794338
New Mexico                16.982737
South Dakota              10.583512
North Dakota               9.537565
Montana                    6.736171
Wyoming                    5.768079
Alaska                     1.087509
United States                   NaN
dtype: float64

In [109]:
density.tail()

state
North Dakota     9.537565
Montana          6.736171
Wyoming          5.768079
Alaska           1.087509
United States         NaN
dtype: float64

### Exercises
Compute the total population of the entire united states, as well as its population density for each year.

Sort the states by population density.

What year saw the biggest change in population for the US as a whole?

Which states had the biggest percentage change in population in that year?

In [114]:
# merged.tail(10)
data2010['area (sq. mi)'].sum()

3790399.0

In [143]:
# total population density
pd.options.display.max_rows = None
final.loc[final.state == 'United States', 'area (sq. mi)'] = data2010['area (sq. mi)'].sum()
final['density'] = final['population']/final['area (sq. mi)']

# add population density to main df
pop_dens_year = 2012
year_data = final[(final.year == pop_dens_year) & (final.ages == 'total')]
year_data = year_data.sort_values('density')
print('Sorted by 2012 population density (ascending): ')
print(', '.join(list(year_data.state)))

# add population change
final_sorted = final[final.ages == 'total'].sort_values('year')
final_sorted = final_sorted.sort_values('state/region', kind='stable')
final_sorted['pop_change'] = final_sorted.population.diff()
final_sorted.loc[final_sorted.year == final_sorted.year.min(), 'pop_change'] = np.nan

# use argmax to find year of greatest change
us_data = final_sorted[final_sorted.state == 'United States']
gt_chng_yr = us_data.iloc[us_data.pop_change.argmax()].year
print(f'Year of greatest change: {gt_chng_yr}, actual change: {us_data.pop_change.max()}')

# add percent change
final_sorted['pct_change'] = final_sorted['pop_change']/(final_sorted['population'] - final_sorted['pop_change'])
final_sorted[final_sorted.year == gt_chng_yr].sort_values('pct_change', ascending=False)

Sorted by 2012 population density (ascending):
Alaska, Wyoming, Montana, North Dakota, South Dakota, New Mexico, Idaho, Nebraska, Nevada, Utah, Kansas, Maine, Oregon, Colorado, Oklahoma, Iowa, Arkansas, Arizona, Mississippi, Minnesota, Vermont, West Virginia, United States, Missouri, Wisconsin, Louisiana, Alabama, Washington, Texas, Michigan, Kentucky, Hawaii, New Hampshire, South Carolina, Tennessee, Georgia, Indiana, North Carolina, Virginia, Illinois, California, Ohio, Pennsylvania, Florida, New York, Delaware, Maryland, Massachusetts, Connecticut, Rhode Island, New Jersey, Puerto Rico, District of Columbia
Year of greatest change: 1992, actual change: 3533289.0

,state/region,ages,year,population,state,area (sq. mi),density,pop_change,pct_change
1383,NV,total,1992,1351367.0,Nevada,110567.0,12.222155,55195.0,0.042583
141,AZ,total,1992,3915740.0,Arizona,114006.0,34.346789,127164.0,0.033565
50,AK,total,1992,588736.0,Alaska,656425.0,0.896882,18543.0,0.032521
242,CO,total,1992,3495939.0,Colorado,104100.0,33.582507,108820.0,0.032128
2153,UT,total,1992,1836799.0,Utah,84904.0,21.633834,57019.0,0.032037
615,ID,total,1992,1071685.0,Idaho,83574.0,12.823187,30369.0,0.029164
2263,WA,total,1992,5160757.0,Washington,71303.0,72.377838,135133.0,0.026889
1495,NM,total,1992,1595442.0,New Mexico,121593.0,13.121167,40137.0,0.025807
519,GA,total,1992,6817203.0,Georgia,59441.0,114.688565,164198.0,0.024680
1783,OR,total,1992,2991755.0,Oregon,98386.0,30.408341,63248.0,0.021597
440,FL,total,1992,13650553.0,Florida,65758.0,207.587716,280755.0,0.020999
2071,TX,total,1992,17759738.0,Texas,268601.0,66.119404,361733.0,0.020792
1287,MT,total,1992,825770.0,Montana,147046.0,5.615726,16090.0,0.019872
537,HI,total,1992,1158613.0,Hawaii,10932.0,105.983626,21859.0,0.019229
2249,VA,total,1992,6414307.0,Virginia,42769.0,149.975613,113090.0,0.017947
339,DE,total,1992,694927.0,Delaware,1954.0,355.643296,11847.0,0.017344
2057,TN,total,1992,5049742.0,Tennessee,42146.0,119.815451,83155.0,0.016743
1591,NC,total,1992,6897214.0,North Carolina,53821.0,128.150982,112934.0,0.016646
237,CA,total,1992,30974659.0,California,163707.0,189.207908,503923.0,0.016538
2441,WY,total,1992,466251.0,Wyoming,97818.0,4.766515,6991.0,0.015222
1769,OK,total,1992,3220517.0,Oklahoma,69903.0,46.071227,45077.0,0.014196
1961,SC,total,1992,3620464.0,South Carolina,32007.0,113.114756,50060.0,0.014021
2501,USA,total,1992,256514231.0,United States,3790399.0,67.674731,3533289.0,0.013967
149,AR,total,1992,2415984.0,Arkansas,53182.0,45.428604,32840.0,0.013780
807,KS,total,1992,2532395.0,Kansas,82282.0,30.777023,33673.0,0.013476
43,AL,total,1992,4154014.0,Alabama,52423.0,79.240295,54858.0,0.013383
1975,SD,total,1992,712801.0,South Dakota,77121.0,9.242632,9132.0,0.012978
1113,MN,total,1992,4495572.0,Minnesota,86943.0,51.707118,54713.0,0.012320
2359,WI,total,1992,5025398.0,Wisconsin,65503.0,76.720120,61055.0,0.012299
825,KY,total,1992,3765469.0,Kentucky,40411.0,93.179308,43141.0,0.011590
999,MD,total,1992,4923369.0,Maryland,12407.0,396.821875,55728.0,0.011449
633,IL,total,1992,11694184.0,Illinois,57918.0,201.909320,125220.0,0.010824
711,IN,total,1992,5674547.0,Indiana,36420.0,155.808539,58159.0,0.010355
1305,NE,total,1992,1611687.0,Nebraska,77358.0,20.834135,15768.0,0.009880
1191,MS,total,1992,2623734.0,Mississippi,48434.0,54.171326,25001.0,0.009620
903,LA,total,1992,4293003.0,Louisiana,51843.0,82.807766,39724.0,0.009340
1209,MO,total,1992,5217101.0,Missouri,69709.0,74.841140,46301.0,0.008954
1479,NJ,total,1992,7880508.0,New Jersey,8722.0,903.520752,65832.0,0.008424
1095,MI,total,1992,9479065.0,Michigan,96810.0,97.914110,78619.0,0.008363
1687,OH,total,1992,11029431.0,Ohio,44828.0,246.038882,83669.0,0.007644
729,IA,total,1992,2818401.0,Iowa,56276.0,50.081758,20788.0,0.007431
2167,VT,total,1992,572751.0,Vermont,9615.0,59.568487,4145.0,0.007290
1401,NH,total,1992,1117785.0,New Hampshire,9351.0,119.536413,7856.0,0.007078
1576,NY,total,1992,18246653.0,New York,54475.0,334.954621,124143.0,0.006850
1865,PA,total,1992,12049450.0,Pennsylvania,46058.0,261.614703,67286.0,0.005616
2345,WV,total,1992,1806451.0,West Virginia,24231.0,74.551236,7716.0,0.004290
1673,ND,total,1992,638223.0,North Dakota,70704.0,9.026689,2470.0,0.003885
1879,RI,total,1992,1012581.0,Rhode Island,1545.0,655.392233,1932.0,0.001912
1017,MA,total,1992,6028709.0,Massachusetts,10555.0,571.170914,10239.0,0.001701
921,ME,total,1992,1238508.0,Maine,35387.0,34.998954,1427.0,0.001154
333,CT,total,1992,3300712.0,Connecticut,5544.0,595.366522,-2183.0,-0.000661
429,DC,total,1992,597567.0,District of Columbia,68.0,8787.750000,-3303.0,-0.005497
2455,PR,total,1992,NaN,Puerto Rico,3515.0,NaN,NaN,NaN

In [154]:
pd.options.display.max_rows = 100

## Multiindexing
You can use multiple columns to define an index, as long as each row has a unique combination of values within those columns. In the following example, we will use the columns "state/region", "year", and "ages" of the population dataframe as an index

We use the `.set_index(['column_name1', 'column_name2, ...])'` command to create a multiindex from existing columns.

Note that many operations require a multiindex to be sorted, so we also call `.sort_index()` on the dataframe. Also, `.set_index()` and `.sort_index()` return a _copy_ of the dataframe, so we assign the output to itself to update the value.

In [150]:
# set index to use multiple columns
final = final.set_index(['state/region','year','ages']) # overwrite old version with new version with index set
final = final.sort_index() # replace itself with a version with a sorted index
final.tail(10) #print last 10 entries

                           population    state  area (sq. mi)   density
state/region year ages
WY           2009 total      559851.0  Wyoming        97818.0  5.723394
                  under18    134960.0  Wyoming        97818.0  1.379705
             2010 total      564222.0  Wyoming        97818.0  5.768079
                  under18    135351.0  Wyoming        97818.0  1.383702
             2011 total      567329.0  Wyoming        97818.0  5.799843
                  under18    135407.0  Wyoming        97818.0  1.384275
             2012 total      576626.0  Wyoming        97818.0  5.894886
                  under18    136526.0  Wyoming        97818.0  1.395714
             2013 total      582658.0  Wyoming        97818.0  5.956552
                  under18    137679.0  Wyoming        97818.0  1.407502

In [155]:
final.loc[('MA',2009,'total'):('WY',2011,'total')]

                           population          state  area (sq. mi)  \
state/region year ages
MA           2009 total     6517613.0  Massachusetts        10555.0
                  under18   1422935.0  Massachusetts        10555.0
             2010 total     6563263.0  Massachusetts        10555.0
                  under18   1415962.0  Massachusetts        10555.0
             2011 total     6606285.0  Massachusetts        10555.0
...                               ...            ...            ...
WY           2009 total      559851.0        Wyoming        97818.0
                  under18    134960.0        Wyoming        97818.0
             2010 total      564222.0        Wyoming        97818.0
                  under18    135351.0        Wyoming        97818.0
             2011 total      567329.0        Wyoming        97818.0

                              density
state/region year ages
MA           2009 total    617.490573
                  under18  134.811464
             2010 total    621.815538
                  under18  134.150829
             2011 total    625.891521
...                               ...
WY           2009 total      5.723394
                  under18    1.379705
             2010 total      5.768079
                  under18    1.383702
             2011 total      5.799843

[1589 rows x 4 columns]

In [156]:
idx = pd.IndexSlice
final.loc[idx[:,2009:2011,'total']]

                         population          state  area (sq. mi)    density
state/region year ages
AK           2009 total    698895.0         Alaska       656425.0   1.064699
             2010 total    713868.0         Alaska       656425.0   1.087509
             2011 total    723375.0         Alaska       656425.0   1.101992
AL           2009 total   4757938.0        Alabama        52423.0  90.760506
             2010 total   4785570.0        Alabama        52423.0  91.287603
...                             ...            ...            ...        ...
WV           2010 total   1854146.0  West Virginia        24231.0  76.519582
             2011 total   1855184.0  West Virginia        24231.0  76.562420
WY           2009 total    559851.0        Wyoming        97818.0   5.723394
             2010 total    564222.0        Wyoming        97818.0   5.768079
             2011 total    567329.0        Wyoming        97818.0   5.799843

[159 rows x 4 columns]

In [193]:
import pandas as pd

# Sample data
data = {
    'State': ['California', 'California', 'Texas', 'Texas'],
    'Year': [2020, 2021, 2020, 2021],
    'under18': [9216956, 9350000, 7351134, 7500000],
    'total': [39538223, 40000000, 29145505, 29500000],
    'Area': [163696, 163696, 268596, 268596]
}

# Create DataFrame
df = pd.DataFrame(data)

print("Original DataFrame:")
print(df)

# Melt the DataFrame to unpivot the population columns
df_melted = pd.melt(df, id_vars=['State', 'Year', 'Area'], value_vars=['under18', 'total'],
                    var_name='Age Category', value_name='Population')

# # Pivot the DataFrame to set 'Age Category' as columns
df_pivoted = df_melted.pivot_table(index=['State', 'Year', 'Area'], columns='Age Category', values='Population')
df_pivoted

# # Flatten the columns and create a MultiIndex on 'Population'
# df_pivoted.columns = pd.MultiIndex.from_product([['Population'], df_pivoted.columns])

# # Reset the index to turn 'State', 'Year', and 'Area' into regular columns
# df_final = df_pivoted.reset_index()

# print("\nDataFrame with MultiIndex for Population:")
# df_final

Original DataFrame:
        State  Year  under18     total    Area
0  California  2020  9216956  39538223  163696
1  California  2021  9350000  40000000  163696
2       Texas  2020  7351134  29145505  268596
3       Texas  2021  7500000  29500000  268596

Age Category                 total    under18
State      Year Area
California 2020 163696  39538223.0  9216956.0
           2021 163696  40000000.0  9350000.0
Texas      2020 268596  29145505.0  7351134.0
           2021 268596  29500000.0  7500000.0

### Stacking and unstacking
Columns can also have multiple levels. In fact, the columns can be thought of as just another index that runs horizontally. This is most easily illustrated by stacking, unstacking, and transposing.

You can convert a level of the row index to a column level using the `.unstack()` command. Conversely, `.stack()` moves a column level to the index

In [64]:
unstacked = final.unstack(level='ages') # you can unstack by level name; this moves the 'ages' categories into the column index
unstacked

                  population              state          area (sq. mi)  \
ages                   total   under18    total  under18         total
state/region year
AK           1990   553290.0  177502.0   Alaska   Alaska      656425.0
             1991   570193.0  182180.0   Alaska   Alaska      656425.0
             1992   588736.0  184878.0   Alaska   Alaska      656425.0
             1993   599434.0  187190.0   Alaska   Alaska      656425.0
             1994   603308.0  187439.0   Alaska   Alaska      656425.0
...                      ...       ...      ...      ...           ...
WY           2009   559851.0  134960.0  Wyoming  Wyoming       97818.0
             2010   564222.0  135351.0  Wyoming  Wyoming       97818.0
             2011   567329.0  135407.0  Wyoming  Wyoming       97818.0
             2012   576626.0  136526.0  Wyoming  Wyoming       97818.0
             2013   582658.0  137679.0  Wyoming  Wyoming       97818.0


ages                under18
state/region year
AK           1990  656425.0
             1991  656425.0
             1992  656425.0
             1993  656425.0
             1994  656425.0
...                     ...
WY           2009   97818.0
             2010   97818.0
             2011   97818.0
             2012   97818.0
             2013   97818.0

[1272 rows x 6 columns]

In [65]:
restacked = unstacked.stack('ages', dropna=False) # stacks the column level back into the row index
# by default, .stack() omits entries with NaN. If you want to preserve the NaN entries, use the option dropna=False
restacked == final # just like the original state_populations dataframe

                           population  state  area (sq. mi)
state/region year ages
AK           1990 total          True   True           True
                  under18        True   True           True
             1991 total          True   True           True
                  under18        True   True           True
             1992 total          True   True           True
...                               ...    ...            ...
WY           2011 under18        True   True           True
             2012 total          True   True           True
                  under18        True   True           True
             2013 total          True   True           True
                  under18        True   True           True

[2544 rows x 3 columns]

In [66]:
final.unstack(level=0) # you can also unstack using integer levels. Here we unstacked level 0, corresponding to state/region

             population                                               \
state/region         AK         AL         AR         AZ          CA
year ages
1990 total     553290.0  4050055.0  2356586.0  3684097.0  29959515.0
     under18   177502.0  1050041.0   620933.0  1006040.0   7980501.0
1991 total     570193.0  4099156.0  2383144.0  3788576.0  30470736.0
     under18   182180.0  1060794.0   626212.0  1028285.0   8245605.0
1992 total     588736.0  4154014.0  2415984.0  3915740.0  30974659.0
     under18   184878.0  1072873.0   638269.0  1055572.0   8439647.0
1993 total     599434.0  4214202.0  2456303.0  4065440.0  31274928.0
     under18   187190.0  1085606.0   643474.0  1094233.0   8624810.0
1994 total     603308.0  4260229.0  2494019.0  4245089.0  31484435.0
     under18   187439.0  1097180.0   653842.0  1119857.0   8790058.0
1995 total     604412.0  4296800.0  2535399.0  4432499.0  31696582.0
     under18   184990.0  1110553.0   667671.0  1173391.0   8920578.0
1996 total     608569.0  4331103.0  2572109.0  4586940.0  32018834.0
     under18   185360.0  1112092.0   677912.0  1215285.0   9079519.0
1997 total     612968.0  4367935.0  2601091.0  4736990.0  32486010.0
     under18   188280.0  1122893.0   680203.0  1237159.0   9135359.0
1998 total     619933.0  4404701.0  2626289.0  4883342.0  32987675.0
     under18   192636.0  1118252.0   683637.0  1285794.0   9163238.0
1999 total     624779.0  4430141.0  2651860.0  5023823.0  33499204.0
     under18   191422.0  1121287.0   681940.0  1332396.0   9207878.0
2000 total     627963.0  4452173.0  2678588.0  5160586.0  33987977.0
     under18   190615.0  1122273.0   680378.0  1373414.0   9267089.0
2001 total     633714.0  4467634.0  2691571.0  5273477.0  34479458.0
     under18   188771.0  1120409.0   679606.0  1399015.0   9325466.0
2002 total     642337.0  4480089.0  2705927.0  5396255.0  34871843.0
     under18   188482.0  1116590.0   678798.0  1427938.0   9365142.0
2003 total     648414.0  4503491.0  2724816.0  5510364.0  35253159.0
     under18   186843.0  1113083.0   679579.0  1453671.0   9404594.0
2004 total     659286.0  4530729.0  2749686.0  5652404.0  35574576.0
     under18   186335.0  1113662.0   683166.0  1484454.0   9418497.0
2005 total     666946.0  4569805.0  2781097.0  5839077.0  35827943.0
     under18   185304.0  1117229.0   689787.0  1529168.0   9405565.0
2006 total     675302.0  4628981.0  2821761.0  6029141.0  36021202.0
     under18   185580.0  1126798.0   697842.0  1574867.0   9370884.0
2007 total     680300.0  4672840.0  2848650.0  6167681.0  36250311.0
     under18   184344.0  1132296.0   702737.0  1607895.0   9335620.0
2008 total     687455.0  4718206.0  2874554.0  6280362.0  36604337.0
     under18   183124.0  1134927.0   705725.0  1628651.0   9321621.0
2009 total     698895.0  4757938.0  2896843.0  6343154.0  36961229.0
     under18   186351.0  1134192.0   707886.0  1627343.0   9294501.0
2010 total     713868.0  4785570.0  2922280.0  6408790.0  37333601.0
     under18   187902.0  1130966.0   711947.0  1628563.0   9284094.0
2011 total     723375.0  4801627.0  2938506.0  6468796.0  37668681.0
     under18   188329.0  1125763.0   710576.0  1616353.0   9252336.0
2012 total     730307.0  4817528.0  2949828.0  6551149.0  37999878.0
     under18   188162.0  1117489.0   710471.0  1617149.0   9209007.0
2013 total     735132.0  4833722.0  2959373.0  6626624.0  38332521.0
     under18   188132.0  1111481.0   709866.0  1616814.0   9174877.0

                                                                               \
state/region         CO         CT        DC        DE          FL         GA
year ages
1990 total    3307618.0  3291967.0  605321.0  669567.0  13033307.0  6512602.0
     under18   881640.0   752666.0  112632.0  165628.0   2988807.0  1747363.0
1991 total    3387119.0  3302895.0  600870.0  683080.0  13369798.0  6653005.0
     under18   896537.0   766304.0  116825.0  169910.0   3045638.0  1773675.0
1992 total    3495939.0  3300712.0  597567.0  694927.0  13650553.0  6817203.0
     under18   925577.0   777264.0  118636.0  174166.0   3120439.0  1817781.0
1993 total    3613734.0  3309175.0  595302.0  706378.0  13927185.0  6978240.0
     under18   947806.0   790749.0  120471.0  176916.0   3214066.0  1865021.0
1994 total    3724168.0  3316121.0  589240.0  717545.0  14239444.0  7157165.0
     under18   966412.0   801231.0  122170.0  180833.0   3299887.0  1906539.0
1995 total    3826653.0  3324144.0  580519.0  729735.0  14537875.0  7328413.0
     under18   984310.0   808623.0  123620.0  181736.0   3366468.0  1949818.0
1996 total    3919972.0  3336685.0  572379.0  740978.0  14853360.0  7501069.0
     under18  1003946.0   811855.0  121210.0  184021.0   3431695.0  1993171.0
1997 total    4018293.0  3349348.0  567739.0  751487.0  15186304.0  7685099.0
     under18  1030557.0   814373.0  119531.0  186607.0   3502269.0  2034163.0
1998 total    4116639.0  3365352.0  565232.0  763335.0  15486559.0  7863536.0
     under18  1060066.0   824600.0  113839.0  189302.0   3557561.0  2078998.0
1999 total    4226018.0  3386401.0  570220.0  774990.0  15759421.0  8045965.0
     under18  1083938.0   834654.0  115003.0  192510.0   3611711.0  2130698.0
2000 total    4326921.0  3411777.0  572046.0  786373.0  16047515.0  8227303.0
     under18  1106676.0   842242.0  114503.0  194914.0   3654880.0  2176576.0
2001 total    4425687.0  3432835.0  574504.0  795699.0  16356966.0  8377038.0
     under18  1126647.0   845850.0  114625.0  196038.0   3714439.0  2215390.0
2002 total    4490406.0  3458749.0  573158.0  806169.0  16689370.0  8508256.0
     under18  1138273.0   848877.0  113822.0  196946.0   3774624.0  2249784.0
2003 total    4528732.0  3484336.0  568502.0  818003.0  17004085.0  8622793.0
     under18  1144597.0   851115.0  111403.0  198045.0   3820876.0  2278710.0
2004 total    4575013.0  3496094.0  567754.0  830803.0  17415318.0  8769252.0
     under18  1146369.0   848979.0  109756.0  199631.0   3890734.0  2308855.0
2005 total    4631888.0  3506956.0  567136.0  845150.0  17842038.0  8925922.0
     under18  1156399.0   844034.0  107187.0  201988.0   3968178.0  2353604.0
2006 total    4720423.0  3517460.0  570681.0  859268.0  18166990.0  9155813.0
     under18  1171832.0   839372.0  105651.0  203729.0   4022912.0  2406014.0
2007 total    4803868.0  3527270.0  574404.0  871749.0  18367842.0  9349988.0
     under18  1189434.0   833484.0  104126.0  205155.0   4031098.0  2456249.0
2008 total    4889730.0  3545579.0  580236.0  883874.0  18527305.0  9504843.0
     under18  1203289.0   826626.0  102257.0  206116.0   4018372.0  2479097.0
2009 total    4972195.0  3561807.0  592228.0  891730.0  18652644.0  9620846.0
     under18  1217213.0   820839.0  102098.0  206213.0   3997283.0  2485781.0
2010 total    5048196.0  3579210.0  605125.0  899711.0  18846054.0  9713248.0
     under18  1226619.0   814187.0  101309.0  205478.0   3999532.0  2490884.0
2011 total    5118400.0  3588948.0  619624.0  907985.0  19083482.0  9810181.0
     under18  1230178.0   805109.0  103906.0  204801.0   4002550.0  2488898.0
2012 total    5189458.0  3591765.0  633427.0  917053.0  19320749.0  9915646.0
     under18  1232864.0   794959.0  107642.0  204586.0   4012421.0  2487831.0
2013 total    5268367.0  3596080.0  646449.0  925749.0  19552860.0  9992167.0
     under18  1237932.0   785566.0  111474.0  203558.0   4026674.0  2489709.0

                                                                      \
state/region         HI         IA         ID          IL         IN
year ages
1990 total    1113491.0  2781018.0  1012384.0  11453316.0  5557798.0
     under18   279983.0   719366.0   313373.0   2940837.0  1437209.0
1991 total    1136754.0  2797613.0  1041316.0  11568964.0  5616388.0
     under18   287871.0   724446.0   316732.0   2988715.0  1450759.0
1992 total    1158613.0  2818401.0  1071685.0  11694184.0  5674547.0
     under18   295124.0   724798.0   324972.0   3033427.0  1461650.0
1993 total    1172838.0  2836972.0  1108768.0  11809579.0  5739019.0
     under18   301473.0   727751.0   333838.0   3066541.0  1473007.0
1994 total    1187536.0  2850746.0  1145140.0  11912585.0  5793526.0
     under18   307517.0   728397.0   344242.0   3110938.0  1491802.0
1995 total    1196854.0  2867373.0  1177322.0  12008437.0  5851459.0
     under18   310325.0   726961.0   349248.0   3152984.0  1507916.0
1996 total    1203755.0  2880001.0  1203083.0  12101997.0  5906013.0
     under18   311213.0   729177.0   353824.0   3192916.0  1517961.0
1997 total    1211640.0  2891119.0  1228520.0  12185715.0  5955267.0
     under18   309465.0   729806.0   357779.0   3222114.0  1539270.0
1998 total    1215233.0  2902872.0  1252330.0  12271847.0  5998881.0
     under18   304576.0   729943.0   362189.0   3225252.0  1551960.0
1999 total    1210300.0  2917634.0  1275674.0  12359020.0  6044970.0
     under18   299680.0   732671.0   366689.0   3240034.0  1566079.0
2000 total    1213519.0  2929067.0  1299430.0  12434161.0  6091866.0
     under18   295352.0   733337.0   370430.0   3244944.0  1574989.0
2001 total    1225948.0  2931997.0  1319962.0  12488445.0  6127760.0
     under18   294133.0   728601.0   373145.0   3243617.0  1579527.0
2002 total    1239613.0  2934234.0  1340372.0  12525556.0  6155967.0
     under18   293600.0   723685.0   375986.0   3238362.0  1580814.0
2003 total    1251154.0  2941999.0  1363380.0  12556006.0  6196638.0
     under18   294519.0   720102.0   379241.0   3225547.0  1582560.0
2004 total    1273569.0  2953635.0  1391802.0  12589773.0  6233007.0
     under18   298103.0   718708.0   384692.0   3211599.0  1586281.0
2005 total    1292729.0  2964454.0  1428241.0  12609903.0  6278616.0
     under18   298497.0   718488.0   394651.0   3197318.0  1593898.0
2006 total    1309731.0  2982644.0  1468669.0  12643955.0  6332669.0
     under18   299313.0   721703.0   404753.0   3181246.0  1603107.0
2007 total    1315675.0  2999212.0  1505105.0  12695866.0  6379599.0
     under18   300207.0   723632.0   415024.0   3170134.0  1609494.0
2008 total    1332213.0  3016734.0  1534320.0  12747038.0  6424806.0
     under18   301094.0   725658.0   422347.0   3153401.0  1611494.0
2009 total    1346717.0  3032870.0  1554439.0  12796778.0  6459325.0
     under18   302796.0   726969.0   426076.0   3138406.0  1609704.0
2010 total    1363731.0  3050314.0  1570718.0  12839695.0  6489965.0
     under18   303812.0   727717.0   428961.0   3122092.0  1605883.0
2011 total    1376897.0  3064102.0  1583930.0  12855970.0  6516336.0
     under18   305396.0   725522.0   428535.0   3089833.0  1598091.0
2012 total    1390090.0  3075039.0  1595590.0  12868192.0  6537782.0
     under18   305981.0   723917.0   427177.0   3057042.0  1589655.0
2013 total    1404054.0  3090416.0  1612136.0  12882135.0  6570902.0
     under18   307266.0   724032.0   427781.0   3023307.0  1586027.0

                                                                     \
state/region         KS         KY         LA         MA         MD
year ages
1990 total    2481349.0  3694048.0  4221532.0  6022639.0  4799770.0
     under18   662641.0   945951.0  1205984.0  1353806.0  1180426.0
1991 total    2498722.0  3722328.0  4253279.0  6018470.0  4867641.0
     under18   672033.0   951512.0  1222330.0  1375110.0  1208898.0
1992 total    2532395.0  3765469.0  4293003.0  6028709.0  4923369.0
     under18   680871.0   963861.0  1237034.0  1390188.0  1235498.0
1993 total    2556547.0  3812206.0  4316428.0  6060569.0  4971889.0
     under18   687262.0   971134.0  1239161.0  1415724.0  1261738.0
1994 total    2580513.0  3849088.0  4347481.0  6095241.0  5023060.0
     under18   693673.0   981439.0  1247631.0  1437069.0  1280772.0
1995 total    2601008.0  3887427.0  4378779.0  6141445.0  5070033.0
     under18   694124.0   984486.0  1250112.0  1453489.0  1300695.0
1996 total    2614554.0  3919536.0  4398877.0  6179756.0  5111986.0
     under18   696298.0   987062.0  1244627.0  1468614.0  1303816.0
1997 total    2635292.0  3952747.0  4421072.0  6226058.0  5157328.0
     under18   704001.0  1002609.0  1239665.0  1478203.0  1321306.0
1998 total    2660598.0  3985391.0  4440344.0  6271838.0  5204464.0
     under18   710402.0   997296.0  1232984.0  1491652.0  1338727.0
1999 total    2678338.0  4018053.0  4460811.0  6317345.0  5254509.0
     under18   713022.0   996382.0  1227167.0  1495818.0  1348659.0
2000 total    2693681.0  4049021.0  4471885.0  6361104.0  5311034.0
     under18   713887.0   994984.0  1217670.0  1501334.0  1356961.0
2001 total    2702162.0  4068132.0  4477875.0  6397634.0  5374691.0
     under18   710923.0   994105.0  1204187.0  1505028.0  1366552.0
2002 total    2713535.0  4089875.0  4497267.0  6417206.0  5440389.0
     under18   709416.0   995251.0  1194819.0  1502652.0  1375354.0
2003 total    2723004.0  4117170.0  4521042.0  6422565.0  5496269.0
     under18   707847.0   998485.0  1188070.0  1493372.0  1379641.0
2004 total    2734373.0  4146101.0  4552238.0  6412281.0  5546935.0
     under18   705456.0   998459.0  1182731.0  1479541.0  1383450.0
2005 total    2745299.0  4182742.0  4576628.0  6403290.0  5592379.0
     under18   704689.0  1004020.0  1177954.0  1464140.0  1382966.0
2006 total    2762931.0  4219239.0  4302665.0  6410084.0  5627367.0
     under18   705277.0  1011295.0  1078779.0  1450202.0  1377756.0
2007 total    2783785.0  4256672.0  4375581.0  6431559.0  5653408.0
     under18   711005.0  1016288.0  1096642.0  1439757.0  1369563.0
2008 total    2808076.0  4289878.0  4435586.0  6468967.0  5684965.0
     under18   714689.0  1022001.0  1108728.0  1429727.0  1359214.0
2009 total    2832704.0  4317074.0  4491648.0  6517613.0  5730388.0
     under18   721841.0  1021710.0  1114228.0  1422935.0  1353631.0
2010 total    2858910.0  4347698.0  4545392.0  6563263.0  5787193.0
     under18   727729.0  1023679.0  1118576.0  1415962.0  1351983.0
2011 total    2869548.0  4366869.0  4575197.0  6606285.0  5840241.0
     under18   726787.0  1021926.0  1116579.0  1407240.0  1348766.0
2012 total    2885398.0  4379730.0  4602134.0  6645303.0  5884868.0
     under18   726668.0  1017350.0  1114620.0  1399417.0  1346235.0
2013 total    2893957.0  4395295.0  4625470.0  6692824.0  5928814.0
     under18   724092.0  1014004.0  1112957.0  1393946.0  1344522.0

                                                           ... area (sq. mi)  \
state/region         ME          MI         MN         MO  ...            ND
year ages                                                  ...
1990 total    1231719.0   9311319.0  4389857.0  5128880.0  ...       70704.0
     under18   308066.0   2459633.0  1176680.0  1316423.0  ...       70704.0
1991 total    1237081.0   9400446.0  4440859.0  5170800.0  ...       70704.0
     under18   309871.0   2484957.0  1191207.0  1332306.0  ...       70704.0
1992 total    1238508.0   9479065.0  4495572.0  5217101.0  ...       70704.0
     under18   310679.0   2501765.0  1213068.0  1349729.0  ...       70704.0
1993 total    1242302.0   9540114.0  4555956.0  5271175.0  ...       70704.0
     under18   310966.0   2522249.0  1226723.0  1365903.0  ...       70704.0
1994 total    1242662.0   9597737.0  4610355.0  5324497.0  ...       70704.0
     under18   311570.0   2535196.0  1238949.0  1378700.0  ...       70704.0
1995 total    1243481.0   9676211.0  4660180.0  5378247.0  ...       70704.0
     under18   309173.0   2556799.0  1245932.0  1393554.0  ...       70704.0
1996 total    1249060.0   9758645.0  4712827.0  5431553.0  ...       70704.0
     under18   307740.0   2569745.0  1252722.0  1408732.0  ...       70704.0
1997 total    1254774.0   9809051.0  4763390.0  5481193.0  ...       70704.0
     under18   305097.0   2582270.0  1264250.0  1419837.0  ...       70704.0
1998 total    1259127.0   9847942.0  4813412.0  5521765.0  ...       70704.0
     under18   304496.0   2586343.0  1275940.0  1428999.0  ...       70704.0
1999 total    1266808.0   9897116.0  4873481.0  5561948.0  ...       70704.0
     under18   302321.0   2591944.0  1283102.0  1428047.0  ...       70704.0
2000 total    1277072.0   9952450.0  4933692.0  5607285.0  ...       70704.0
     under18   301407.0   2596114.0  1289715.0  1428383.0  ...       70704.0
2001 total    1285692.0   9991120.0  4982796.0  5641142.0  ...       70704.0
     under18   300088.0   2593310.0  1291261.0  1426575.0  ...       70704.0
2002 total    1295960.0  10015710.0  5018935.0  5674825.0  ...       70704.0
     under18   298595.0   2584310.0  1288795.0  1424513.0  ...       70704.0
2003 total    1306513.0  10041152.0  5053572.0  5709403.0  ...       70704.0
     under18   296786.0   2569080.0  1283687.0  1421927.0  ...       70704.0
2004 total    1313688.0  10055315.0  5087713.0  5747741.0  ...       70704.0
     under18   294791.0   2553314.0  1281946.0  1420956.0  ...       70704.0
2005 total    1318787.0  10051137.0  5119598.0  5790300.0  ...       70704.0
     under18   292039.0   2531839.0  1280557.0  1422978.0  ...       70704.0
2006 total    1323619.0  10036081.0  5163555.0  5842704.0  ...       70704.0
     under18   288945.0   2503548.0  1282381.0  1428324.0  ...       70704.0
2007 total    1327040.0  10001284.0  5207203.0  5887612.0  ...       70704.0
     under18   286185.0   2470063.0  1285074.0  1431346.0  ...       70704.0
2008 total    1330509.0   9946889.0  5247018.0  5923916.0  ...       70704.0
     under18   282204.0   2418879.0  1284179.0  1428945.0  ...       70704.0
2009 total    1329590.0   9901591.0  5281203.0  5961088.0  ...       70704.0
     under18   277946.0   2372603.0  1284103.0  1426603.0  ...       70704.0
2010 total    1327366.0   9876149.0  5310337.0  5996063.0  ...       70704.0
     under18   273061.0   2333121.0  1282693.0  1424042.0  ...       70704.0
2011 total    1327844.0   9874589.0  5347108.0  6010065.0  ...       70704.0
     under18   268737.0   2299116.0  1280424.0  1414444.0  ...       70704.0
2012 total    1328501.0   9882519.0  5379646.0  6024522.0  ...       70704.0
     under18   264846.0   2269365.0  1278050.0  1405015.0  ...       70704.0
2013 total    1328302.0   9895622.0  5420380.0  6044171.0  ...       70704.0
     under18   261276.0   2245201.0  1279111.0  1397685.0  ...       70704.0

                                                                             \
state/region       NE      NH      NJ        NM        NV       NY       OH
year ages
1990 total    77358.0  9351.0  8722.0  121593.0  110567.0  54475.0  44828.0
     under18  77358.0  9351.0  8722.0  121593.0  110567.0  54475.0  44828.0
1991 total    77358.0  9351.0  8722.0  121593.0  110567.0  54475.0  44828.0
     under18  77358.0  9351.0  8722.0  121593.0  110567.0  54475.0  44828.0
1992 total    77358.0  9351.0  8722.0  121593.0  110567.0  54475.0  44828.0
     under18  77358.0  9351.0  8722.0  121593.0  110567.0  54475.0  44828.0
1993 total    77358.0  9351.0  8722.0  121593.0  110567.0  54475.0  44828.0
     under18  77358.0  9351.0  8722.0  121593.0  110567.0  54475.0  44828.0
1994 total    77358.0  9351.0  8722.0  121593.0  110567.0  54475.0  44828.0
     under18  77358.0  9351.0  8722.0  121593.0  110567.0  54475.0  44828.0
1995 total    77358.0  9351.0  8722.0  121593.0  110567.0  54475.0  44828.0
     under18  77358.0  9351.0  8722.0  121593.0  110567.0  54475.0  44828.0
1996 total    77358.0  9351.0  8722.0  121593.0  110567.0  54475.0  44828.0
     under18  77358.0  9351.0  8722.0  121593.0  110567.0  54475.0  44828.0
1997 total    77358.0  9351.0  8722.0  121593.0  110567.0  54475.0  44828.0
     under18  77358.0  9351.0  8722.0  121593.0  110567.0  54475.0  44828.0
1998 total    77358.0  9351.0  8722.0  121593.0  110567.0  54475.0  44828.0
     under18  77358.0  9351.0  8722.0  121593.0  110567.0  54475.0  44828.0
1999 total    77358.0  9351.0  8722.0  121593.0  110567.0  54475.0  44828.0
     under18  77358.0  9351.0  8722.0  121593.0  110567.0  54475.0  44828.0
2000 total    77358.0  9351.0  8722.0  121593.0  110567.0  54475.0  44828.0

You can switch the row and column index using the transpose function `.T`

In [67]:
final.unstack(level=0).T

year                              1990                   1991             \
ages                             total    under18       total    under18
              state/region
population    AK              553290.0   177502.0    570193.0   182180.0
              AL             4050055.0  1050041.0   4099156.0  1060794.0
              AR             2356586.0   620933.0   2383144.0   626212.0
              AZ             3684097.0  1006040.0   3788576.0  1028285.0
              CA            29959515.0  7980501.0  30470736.0  8245605.0
...                                ...        ...         ...        ...
area (sq. mi) VT                9615.0     9615.0      9615.0     9615.0
              WA               71303.0    71303.0     71303.0    71303.0
              WI               65503.0    65503.0     65503.0    65503.0
              WV               24231.0    24231.0     24231.0    24231.0
              WY               97818.0    97818.0     97818.0    97818.0

year                              1992                   1993             \
ages                             total    under18       total    under18
              state/region
population    AK              588736.0   184878.0    599434.0   187190.0
              AL             4154014.0  1072873.0   4214202.0  1085606.0
              AR             2415984.0   638269.0   2456303.0   643474.0
              AZ             3915740.0  1055572.0   4065440.0  1094233.0
              CA            30974659.0  8439647.0  31274928.0  8624810.0
...                                ...        ...         ...        ...
area (sq. mi) VT                9615.0     9615.0      9615.0     9615.0
              WA               71303.0    71303.0     71303.0    71303.0
              WI               65503.0    65503.0     65503.0    65503.0
              WV               24231.0    24231.0     24231.0    24231.0
              WY               97818.0    97818.0     97818.0    97818.0

year                              1994                   1995             \
ages                             total    under18       total    under18
              state/region
population    AK              603308.0   187439.0    604412.0   184990.0
              AL             4260229.0  1097180.0   4296800.0  1110553.0
              AR             2494019.0   653842.0   2535399.0   667671.0
              AZ             4245089.0  1119857.0   4432499.0  1173391.0
              CA            31484435.0  8790058.0  31696582.0  8920578.0
...                                ...        ...         ...        ...
area (sq. mi) VT                9615.0     9615.0      9615.0     9615.0
              WA               71303.0    71303.0     71303.0    71303.0
              WI               65503.0    65503.0     65503.0    65503.0
              WV               24231.0    24231.0     24231.0    24231.0
              WY               97818.0    97818.0     97818.0    97818.0

year                              1996                   1997             \
ages                             total    under18       total    under18
              state/region
population    AK              608569.0   185360.0    612968.0   188280.0
              AL             4331103.0  1112092.0   4367935.0  1122893.0
              AR             2572109.0   677912.0   2601091.0   680203.0
              AZ             4586940.0  1215285.0   4736990.0  1237159.0
              CA            32018834.0  9079519.0  32486010.0  9135359.0
...                                ...        ...         ...        ...
area (sq. mi) VT                9615.0     9615.0      9615.0     9615.0
              WA               71303.0    71303.0     71303.0    71303.0
              WI               65503.0    65503.0     65503.0    65503.0
              WV               24231.0    24231.0     24231.0    24231.0
              WY               97818.0    97818.0     97818.0    97818.0

year                              1998                   1999             \
ages                             total    under18       total    under18
              state/region
population    AK              619933.0   192636.0    624779.0   191422.0
              AL             4404701.0  1118252.0   4430141.0  1121287.0
              AR             2626289.0   683637.0   2651860.0   681940.0
              AZ             4883342.0  1285794.0   5023823.0  1332396.0
              CA            32987675.0  9163238.0  33499204.0  9207878.0
...                                ...        ...         ...        ...
area (sq. mi) VT                9615.0     9615.0      9615.0     9615.0
              WA               71303.0    71303.0     71303.0    71303.0
              WI               65503.0    65503.0     65503.0    65503.0
              WV               24231.0    24231.0     24231.0    24231.0
              WY               97818.0    97818.0     97818.0    97818.0

year                              2000                   2001             \
ages                             total    under18       total    under18
              state/region
population    AK              627963.0   190615.0    633714.0   188771.0
              AL             4452173.0  1122273.0   4467634.0  1120409.0
              AR             2678588.0   680378.0   2691571.0   679606.0
              AZ             5160586.0  1373414.0   5273477.0  1399015.0
              CA            33987977.0  9267089.0  34479458.0  9325466.0
...                                ...        ...         ...        ...
area (sq. mi) VT                9615.0     9615.0      9615.0     9615.0
              WA               71303.0    71303.0     71303.0    71303.0
              WI               65503.0    65503.0     65503.0    65503.0
              WV               24231.0    24231.0     24231.0    24231.0
              WY               97818.0    97818.0     97818.0    97818.0

year                              2002                   2003             \
ages                             total    under18       total    under18
              state/region
population    AK              642337.0   188482.0    648414.0   186843.0
              AL             4480089.0  1116590.0   4503491.0  1113083.0
              AR             2705927.0   678798.0   2724816.0   679579.0
              AZ             5396255.0  1427938.0   5510364.0  1453671.0
              CA            34871843.0  9365142.0  35253159.0  9404594.0
...                                ...        ...         ...        ...
area (sq. mi) VT                9615.0     9615.0      9615.0     9615.0
              WA               71303.0    71303.0     71303.0    71303.0
              WI               65503.0    65503.0     65503.0    65503.0
              WV               24231.0    24231.0     24231.0    24231.0
              WY               97818.0    97818.0     97818.0    97818.0

year                              2004                   2005             \
ages                             total    under18       total    under18
              state/region
population    AK              659286.0   186335.0    666946.0   185304.0
              AL             4530729.0  1113662.0   4569805.0  1117229.0
              AR             2749686.0   683166.0   2781097.0   689787.0
              AZ             5652404.0  1484454.0   5839077.0  1529168.0
              CA            35574576.0  9418497.0  35827943.0  9405565.0
...                                ...        ...         ...        ...
area (sq. mi) VT                9615.0     9615.0      9615.0     9615.0
              WA               71303.0    71303.0     71303.0    71303.0
              WI               65503.0    65503.0     65503.0    65503.0
              WV               24231.0    24231.0     24231.0    24231.0
              WY               97818.0    97818.0     97818.0    97818.0

year                              2006                   2007             \
ages                             total    under18       total    under18
              state/region
population    AK              675302.0   185580.0    680300.0   184344.0
              AL             4628981.0  1126798.0   4672840.0  1132296.0
              AR             2821761.0   697842.0   2848650.0   702737.0
              AZ             6029141.0  1574867.0   6167681.0  1607895.0
              CA            36021202.0  9370884.0  36250311.0  9335620.0
...                                ...        ...         ...        ...
area (sq. mi) VT                9615.0     9615.0      9615.0     9615.0
              WA               71303.0    71303.0     71303.0    71303.0
              WI               65503.0    65503.0     65503.0    65503.0
              WV               24231.0    24231.0     24231.0    24231.0
              WY               97818.0    97818.0     97818.0    97818.0

year                              2008                   2009             \
ages                             total    under18       total    under18
              state/region
population    AK              687455.0   183124.0    698895.0   186351.0
              AL             4718206.0  1134927.0   4757938.0  1134192.0
              AR             2874554.0   705725.0   2896843.0   707886.0
              AZ             6280362.0  1628651.0   6343154.0  1627343.0
              CA            36604337.0  9321621.0  36961229.0  9294501.0
...                                ...        ...         ...        ...
area (sq. mi) VT                9615.0     9615.0      9615.0     9615.0
              WA               71303.0    71303.0     71303.0    71303.0
              WI               65503.0    65503.0     65503.0    65503.0
              WV               24231.0    24231.0     24231.0    24231.0
              WY               97818.0    97818.0     97818.0    97818.0

year                              2010                   2011             \
ages                             total    under18       total    under18
              state/region
population    AK              713868.0   187902.0    723375.0   188329.0
              AL             4785570.0  1130966.0   4801627.0  1125763.0
              AR             2922280.0   711947.0   2938506.0   710576.0
              AZ             6408790.0  1628563.0   6468796.0  1616353.0
              CA            37333601.0  9284094.0  37668681.0  9252336.0
...                                ...        ...         ...        ...
area (sq. mi) VT                9615.0     9615.0      9615.0     9615.0
              WA               71303.0    71303.0     71303.0    71303.0
              WI               65503.0    65503.0     65503.0    65503.0
              WV               24231.0    24231.0     24231.0    24231.0
              WY               97818.0    97818.0     97818.0    97818.0

year                              2012                   2013
ages                             total    under18       total    under18
              state/region
population    AK              730307.0   188162.0    735132.0   188132.0
              AL             4817528.0  1117489.0   4833722.0  1111481.0
              AR             2949828.0   710471.0   2959373.0   709866.0
              AZ             6551149.0  1617149.0   6626624.0  1616814.0
              CA            37999878.0  9209007.0  38332521.0  9174877.0
...                                ...        ...         ...        ...
area (sq. mi) VT                9615.0     9615.0      9615.0     9615.0
              WA               71303.0    71303.0     71303.0    71303.0
              WI               65503.0    65503.0     65503.0    65503.0
              WV               24231.0    24231.0     24231.0    24231.0
              WY               97818.0    97818.0     97818.0    97818.0

[159 rows x 48 columns]

### Pivoting
Pivoting is another advanced way to transform data. It creates a new dataframe using the values of columns as `index` and `column` values. 

You can then aggregate using `aggfunc` the elements of another column, which becomes the `values` of this new dataframe.

In [191]:
pokedex_df.head()

,Pokemon,HP,Atk,Def,SpAtk,SpDef,Speed,Total,Type I,Type II,Ability I,Ability II,Hidden Ability,Color,Nickname
Index,,,,,,,,,,,,,,,
1.0,Bulbasaur,45,49,49,65,65,45,318,Grass,Poison,Overgrow,,Chlorophyll,Green,None
2.0,Ivysaur,60,62,63,80,80,60,405,Grass,Poison,Overgrow,,Chlorophyll,Green,None
3.0,Venusaur,80,82,83,100,100,80,525,Grass,Poison,Overgrow,,Chlorophyll,Green,None
4.0,Charmander,39,52,43,60,50,65,309,Fire,,Blaze,,Solar Power,Red,Abby
5.0,Charmeleon,58,64,58,80,65,80,405,Fire,,Blaze,,Solar Power,Red,None

In [68]:
# let's create a table which lists all pokemon for given type combinations
pokedex_df.pivot_table(values='Pokemon', # line breaks within parentheses automatically continue onto next line
                       index='Type I', # values of Type I become index entries
                       columns='Type II', # likewise Type II become columns
                       aggfunc=lambda x:", ".join(x)).fillna('') # the lambda function here just joins a list of strings using a comma
                      # we also fill nan values with empty string for aesthetics

Type II,,Bug,Dark,Dragon,Electric,Fairy,Fighting,Fire,Flying,Ghost,Grass,Ground,Ice,Normal,Poison,Psychic,Rock,Steel,Water
Type I,,,,,,,,,,,,,,,,,,,
Bug,"Caterpie, Metapod, Pinsir, Pineco, Wurmple, Si...",,,,"Joltik, Galvantula, Charjabug, Vikavolt","Cutiefly, Ribombee","Heracross, Buzzwole, Pheromosa","Larvesta, Volcarona","Butterfree, Scyther, Ledyba, Ledian, Yanma, Be...",Shedinja,"Paras, Parasect, Wormadam (P), Sewaddle, Swadl...","Nincada, Wormadam (S)",,,"Weedle, Kakuna, Beedrill, Venonat, Venomoth, S...",,"Shuckle, Dwebble, Crustle","Forretress, Scizor, Wormadam (T), Escavalier, ...","Surskit, Wimpod, Golisopod"
Dark,"Umbreon, Poochyena, Mightyena, Absol, Darkrai,...",,,"Deino, Zweilous, Hydreigon, Guzzlord",,,"Scraggy, Scrafty","Houndour, Houndoom","Murkrow, Honchkrow, Vullaby, Mandibuzz, Yveltal",Sableye,,,"Sneasel, Weavile",,,"Inkay, Malamar",,"Pawniard, Bisharp",
Dragon,"Dratini, Dragonair, Bagon, Shelgon, Axew, Frax...",,,,Zekrom,,"Hakamo-o, Kommo-o",Reshiram,"Dragonite, Altaria, Salamence, Rayquaza",,,"Gible, Gabite, Garchomp, Zygarde",Kyurem,,,"Latias, Latios",,,
Electric,"Pikachu, Raichu, Voltorb, Electrode, Electabuz...",,,,,"Dedenne, Tapu Koko",,Rotom (Heat),"Zapdos, Rotom (Spin), Emolga, Thundurus",Rotom,Rotom (Cut),,Rotom (Frost),"Helioptile, Heliolisk",,,,"Magnemite, Magneton, Magnezone, Togedemaru",Rotom (Wash)
Fairy,"Clefairy, Clefable, Cleffa, Togepi, Snubbull, ...",,,,,,,,"Togetic, Togekiss",,,,,,,,,,
Fighting,"Mankey, Primeape, Machop, Machoke, Machamp, Hi...",,Pangoro,,,,,,Hawlucha,Marshadow,,,Crabominable,,,"Meditite, Medicham",,Lucario,
Fire,"Charmander, Charmeleon, Vulpix, Ninetales, Gro...",,Incineroar,Turtonator,,,"Combusken, Blaziken, Monferno, Infernape, Pign...",,"Charizard, Moltres, Ho-oh, Fletchinder, Talonf...",,,"Numel, Camerupt",,"Litleo, Pyroar",,"Darmanitan (Z), Delphox",Magcargo,Heatran,Volcanion
Flying,Tornadus,,,"Noibat, Noivern",,,,,,,,,,,,,,,
Ghost,"Misdreavus, Shuppet, Banette, Duskull, Dusclop...",,Spiritomb,"Giratina, Giratina (O)",,Mimikyu,,"Litwick, Lampent, Chandelure","Drifloon, Drifblim",,"Phantump, Trevenant, Pumpkaboo, Gourgeist, Dhe...","Sandygast, Palossand",,,"Gastly, Haunter, Gengar",,,,
Grass,"Tangela, Chikorita, Bayleef, Meganium, Belloss...",,"Nuzleaf, Shiftry, Cacturne",,,"Cottonee, Whimsicott, Morelull, Shiinotic, Tap...","Breloom, Virizion, Chesnaught",,"Hoppip, Skiploom, Jumpluff, Tropius, Shaymin (...",Decidueye,,Torterra,,,"Bulbasaur, Ivysaur, Venusaur, Oddish, Gloom, V...","Exeggcute, Exeggutor",,"Ferroseed, Ferrothorn, Kartana",
Ground,"Sandshrew, Sandslash, Diglett, Dugtrio, Cubone...",,"Sandile, Krokorok, Krookodile","Vibrava, Flygon",Stunfisk,,,,"Gligar, Gliscor, Landorus","Golett, Golurk",,,,,,"Baltoy, Claydol","Rhyhorn, Rhydon, Rhyperior",Excadrill,
Ice,"Snorunt, Glalie, Regice, Glaceon, Vanillite, V...",,,,,,,,"Articuno, Delibird",Froslass,"Snover, Abomasnow","Swinub, Piloswine, Mamoswine",,,,"Jynx, Smoochum",,,"Spheal, Sealeo, Walrein"
Normal,"Rattata, Raticate, Meowth, Persian, Lickitung,...",,,Drampa,,"Jigglypuff, Wigglytuff, Igglybuff, Azurill","Meloetta (P), Stufful, Bewear",,"Pidgey, Pidgeotto, Pidgeot, Spearow, Fearow, F...",,"Deerling, Sawsbuck",Diggersby,,,,"Girafarig, Meloetta (A), Oranguru",,,Bibarel
Poison,"Ekans, Arbok, Nidoran♀, Nidorina, Nidoran♂, Ni...",Skorupi,"Stunky, Skuntank, Drapion",Dragalge,,,"Croagunk, Toxicroak","Salandit, Salazzle","Zubat, Golbat, Crobat",,,"Nidoqueen, Nidoking",,,,,,,"Skrelp, Mareanie, Toxapex"
Psychic,"Abra, Kadabra, Alakazam, Drowzee, Hypno, Mewtw...",,Hoopa (U),,,"Mr. Mime, Ralts, Kirlia, Gardevoir, Mime Jr., ...",Gallade,Victini,"Natu, Xatu, Lugia, Woobat, Swoobat, Sigilyph","Hoopa (C), Lunala",Celebi,,,,,,,Solgaleo,
Rock,"Sudowoodo, Nosepass, Regirock, Cranidos, Rampa...","Anorith, Armaldo",Tyranitar,"Tyrunt, Tyrantrum",,"Carbink, Diancie",Terrakion,,"Aerodactyl, Archen, Archeops, Minior (meteor),...",,"Lileep, Cradily","Geodude, Graveler, Golem, Onix, Larvitar, Pupitar","Amaura, Aurorus",,Nihilego,"Lunatone, Solrock",,"Shieldon, Bastiodon, Probopass","Omanyte, Omastar, Kabuto, Kabutops, Binacle, B..."
Steel,"Registeel, Klink, Klang, Klinklang",,,Dialga,,"Mawile, Klefki, Magearna",Cobalion,,"Skarmory, Celesteela","Honedge, Doublade, Aegislash",,Steelix,,,,"Beldum, Metang, Metagross, Jirachi, Bronzor, B...","Aron, Lairon, Aggron",,
Water,"Squirtle, Wartortle, Blastoise, Psyduck, Goldu...","Dewpider, Araquanid","Carvanha, Sharpedo, Crawdaunt, Greninja","Kingdra, Palkia","Chinchou, Lanturn","Marill, Azumarill, Primarina, Tapu Fini","Poliwrath, Keldeo",,"Gyarados, Mantine, Wingull, Pelipper, Mantyke,...","Frillish, Jellicent","Lotad, Lombre, Ludicolo","Wooper, Quagsire, Marshtomp, Swampert, Barboac...","Dewgong, Cloyster, Lapras",,"Tentacool, Tentacruel, Qwilfish","Slowpoke, Slowbro, Starmie, Slowking, Bruxish","Corsola, Relicanth, Tirtouga, Carracosta",Empoleon,

In [69]:
# compute the average stats for each type combination
pokedex_df.unstack()
pokedex_df.pivot_table(values='Total',
                       index='Type I', 
                       columns='Type II', 
                       aggfunc=lambda x: np.mean(x)).fillna('')

ValueError: Columns with duplicate values are not supported in stack

In [ ]:
# You can compute multiple aggregations on multiple columns by passing a dict
# into the aggfunc argument: aggfunc={'column_name':[list_of_function_names]}
# Note that in this case, the 'value' argument is ignored
pokedex_df.pivot_table(index='Type I', 
                       columns='Type II', 
                       aggfunc={'Total':[lambda x: np.mean(x),lambda x: np.std(x)], 
                                'Atk':[lambda x: np.mean(x),lambda x: np.std(x)]}).fillna('')

# Exercise
Using this data (or any other data you're interested in and you find online), put together an analysis using pandas that investigates an interesting question.

It can be serious or silly. Like "Do states with higher population density tend to vote democratic?" (you'd need to pull additional data for this) or "Do pokemon whose names start with the letter D have better stats than those who start with F?"

We'll ask some volunteers to present their analysis at the end